alter table GAZ_NOTIFICARE_OSD_ATR add constraint FK_GAZ_NOTIFICARE_OSD_ATR_ON_ID_SIRUTA foreign key (ID_SIRUTA_ID) references GAZ_SIRUTA(ID);
create index IDX_GAZ_NOTIFICARE_OSD_ATR_ON_ID_SIRUTA on GAZ_NOTIFICARE_OSD_ATR (ID_SIRUTA_ID);
