alter table GAZ_SOCIETATI_EXECUTIE add constraint FK_GAZ_SOCIETATI_EXECUTIE_ON_ID_LOCATII foreign key (ID_LOCATII_ID) references GAZ_LOCATII(ID);
create index IDX_GAZ_SOCIETATI_EXECUTIE_ON_ID_LOCATII on GAZ_SOCIETATI_EXECUTIE (ID_LOCATII_ID);
