alter table GAZ_PARTENERI add constraint FK_GAZ_PARTENERI_ON_ID_TIP_PERSOANA foreign key (ID_TIP_PERSOANA_ID) references GAZ_TIP_PERSOANA(ID);
create index IDX_GAZ_PARTENERI_ON_ID_TIP_PERSOANA on GAZ_PARTENERI (ID_TIP_PERSOANA_ID);
