alter table GAZ_APARATE_SOLICITATE add constraint FK_GAZ_APARATE_SOLICITATE_ON_ID_APARATE foreign key (ID_APARATE_ID) references GAZ_TIP_APARATE(ID);
create index IDX_GAZ_APARATE_SOLICITATE_ON_ID_APARATE on GAZ_APARATE_SOLICITATE (ID_APARATE_ID);
