alter table GAZ_CERERI_RACORDARE add constraint FK_GAZ_CERERI_RACORDARE_ON_ID_EMAIL_MAN foreign key (ID_EMAIL_MAN_ID) references GAZ_EMAIL(ID);
create index IDX_GAZ_CERERI_RACORDARE_ON_ID_EMAIL_MAN on GAZ_CERERI_RACORDARE (ID_EMAIL_MAN_ID);
