alter table GAZ_INSTALATORI_OSD add constraint FK_GAZ_INSTALATORI_OSD_ON_ID_SIRUTA foreign key (ID_SIRUTA_ID) references GAZ_SIRUTA(ID);
create index IDX_GAZ_INSTALATORI_OSD_ON_ID_SIRUTA on GAZ_INSTALATORI_OSD (ID_SIRUTA_ID);
