alter table GAZ_CERERI_RACORDARE add constraint FK_GAZ_CERERI_RACORDARE_ON_ID_CI_CIF_SOL foreign key (ID_CI_CIF_SOL_ID) references GAZ_CI_CIF(ID);
create index IDX_GAZ_CERERI_RACORDARE_ON_ID_CI_CIF_SOL on GAZ_CERERI_RACORDARE (ID_CI_CIF_SOL_ID);
