alter table GAZ_CONTRACTE_RACORDARE_SD add constraint FK_GAZ_CONTRACTE_RACORDARE_SD_ON_ID_FAX foreign key (ID_FAX_ID) references GAZ_TELEFOANE(ID);
create index IDX_GAZ_CONTRACTE_RACORDARE_SD_ON_ID_FAX on GAZ_CONTRACTE_RACORDARE_SD (ID_FAX_ID);
