alter table GAZ_CERERI_RACORDARE add constraint FK_GAZ_CERERI_RACORDARE_ON_ID_CI_CIF_MAN foreign key (ID_CI_CIF_MAN_ID) references GAZ_CI_CIF(ID);
create index IDX_GAZ_CERERI_RACORDARE_ON_ID_CI_CIF_MAN on GAZ_CERERI_RACORDARE (ID_CI_CIF_MAN_ID);
