update GAZ_ACORD_TEHNIC_RACORDARE set MOD_SD = false where MOD_SD is null ;
alter table GAZ_ACORD_TEHNIC_RACORDARE alter column MOD_SD set not null ;
update GAZ_ACORD_TEHNIC_RACORDARE set EXTINDERE_CONDUCTA = false where EXTINDERE_CONDUCTA is null ;
alter table GAZ_ACORD_TEHNIC_RACORDARE alter column EXTINDERE_CONDUCTA set not null ;
update GAZ_ACORD_TEHNIC_RACORDARE set REDIMENSIONARE_CONDUCTA = false where REDIMENSIONARE_CONDUCTA is null ;
alter table GAZ_ACORD_TEHNIC_RACORDARE alter column REDIMENSIONARE_CONDUCTA set not null ;
update GAZ_ACORD_TEHNIC_RACORDARE set CORECTOR = false where CORECTOR is null ;
alter table GAZ_ACORD_TEHNIC_RACORDARE alter column CORECTOR set not null ;
update GAZ_ACORD_TEHNIC_RACORDARE set RACORD_NOU = false where RACORD_NOU is null ;
alter table GAZ_ACORD_TEHNIC_RACORDARE alter column RACORD_NOU set not null ;
update GAZ_ACORD_TEHNIC_RACORDARE set RACORD_EXISTENT = false where RACORD_EXISTENT is null ;
alter table GAZ_ACORD_TEHNIC_RACORDARE alter column RACORD_EXISTENT set not null ;
update GAZ_ACORD_TEHNIC_RACORDARE set POST_NOU = false where POST_NOU is null ;
alter table GAZ_ACORD_TEHNIC_RACORDARE alter column POST_NOU set not null ;
update GAZ_ACORD_TEHNIC_RACORDARE set POST_EXISTENT = false where POST_EXISTENT is null ;
alter table GAZ_ACORD_TEHNIC_RACORDARE alter column POST_EXISTENT set not null ;
update GAZ_ACORD_TEHNIC_RACORDARE set TEREN_PRIVAT = false where TEREN_PRIVAT is null ;
alter table GAZ_ACORD_TEHNIC_RACORDARE alter column TEREN_PRIVAT set not null ;
update GAZ_ACORD_TEHNIC_RACORDARE set TEREN_PUBLIC = false where TEREN_PUBLIC is null ;
alter table GAZ_ACORD_TEHNIC_RACORDARE alter column TEREN_PUBLIC set not null ;
