alter table GAZ_INSTALATORI_OSD add constraint FK_GAZ_INSTALATORI_OSD_ON_ID_PARTENERI foreign key (ID_PARTENERI_ID) references GAZ_PARTENERI(ID);
create index IDX_GAZ_INSTALATORI_OSD_ON_ID_PARTENERI on GAZ_INSTALATORI_OSD (ID_PARTENERI_ID);
