alter table GAZ_NOTIFICARE_OSD_ATR add constraint FK_GAZ_NOTIFICARE_OSD_ATR_ON_ID_FAX foreign key (ID_FAX_ID) references GAZ_TELEFOANE(ID);
create index IDX_GAZ_NOTIFICARE_OSD_ATR_ON_ID_FAX on GAZ_NOTIFICARE_OSD_ATR (ID_FAX_ID);
