update GAZ_CERERI_RACORDARE set TIP_NOU = false where TIP_NOU is null ;
alter table GAZ_CERERI_RACORDARE alter column TIP_NOU set not null ;
update GAZ_CERERI_RACORDARE set TIP_EXISTENT = false where TIP_EXISTENT is null ;
alter table GAZ_CERERI_RACORDARE alter column TIP_EXISTENT set not null ;
update GAZ_CERERI_RACORDARE set TIP_CASNIC = false where TIP_CASNIC is null ;
alter table GAZ_CERERI_RACORDARE alter column TIP_CASNIC set not null ;
update GAZ_CERERI_RACORDARE set TIP_NONCASNIC = false where TIP_NONCASNIC is null ;
alter table GAZ_CERERI_RACORDARE alter column TIP_NONCASNIC set not null ;
update GAZ_CERERI_RACORDARE set R_OSD_POSTA_DOM = false where R_OSD_POSTA_DOM is null ;
alter table GAZ_CERERI_RACORDARE alter column R_OSD_POSTA_DOM set not null ;
update GAZ_CERERI_RACORDARE set R_OSD_POSTA_LOC_CONS = false where R_OSD_POSTA_LOC_CONS is null ;
alter table GAZ_CERERI_RACORDARE alter column R_OSD_POSTA_LOC_CONS set not null ;
update GAZ_CERERI_RACORDARE set R_OSD_POSTA_MAN = false where R_OSD_POSTA_MAN is null ;
alter table GAZ_CERERI_RACORDARE alter column R_OSD_POSTA_MAN set not null ;
update GAZ_CERERI_RACORDARE set R_OSD_SEDIU = false where R_OSD_SEDIU is null ;
alter table GAZ_CERERI_RACORDARE alter column R_OSD_SEDIU set not null ;
update GAZ_CERERI_RACORDARE set COM_EMAIL = false where COM_EMAIL is null ;
alter table GAZ_CERERI_RACORDARE alter column COM_EMAIL set not null ;
update GAZ_CERERI_RACORDARE set COM_FAX = false where COM_FAX is null ;
alter table GAZ_CERERI_RACORDARE alter column COM_FAX set not null ;
update GAZ_CERERI_RACORDARE set COM_SEDIU = false where COM_SEDIU is null ;
alter table GAZ_CERERI_RACORDARE alter column COM_SEDIU set not null ;
update GAZ_CERERI_RACORDARE set COM_TELEFON = false where COM_TELEFON is null ;
alter table GAZ_CERERI_RACORDARE alter column COM_TELEFON set not null ;
update GAZ_CERERI_RACORDARE set COM_ALTE = false where COM_ALTE is null ;
alter table GAZ_CERERI_RACORDARE alter column COM_ALTE set not null ;
update GAZ_CERERI_RACORDARE set DA_AFISARE_SITE = false where DA_AFISARE_SITE is null ;
alter table GAZ_CERERI_RACORDARE alter column DA_AFISARE_SITE set not null ;
update GAZ_CERERI_RACORDARE set NU_AFISARE_SITE = false where NU_AFISARE_SITE is null ;
alter table GAZ_CERERI_RACORDARE alter column NU_AFISARE_SITE set not null ;
