alter table GAZ_VERIFICATOR add constraint FK_GAZ_VERIFICATOR_ON_ID_TELEFOANE foreign key (ID_TELEFOANE_ID) references GAZ_TELEFOANE(ID);
create index IDX_GAZ_VERIFICATOR_ON_ID_TELEFOANE on GAZ_VERIFICATOR (ID_TELEFOANE_ID);
