alter table GAZ_VERIFICATOR add constraint FK_GAZ_VERIFICATOR_ON_ID_LOCATII foreign key (ID_LOCATII_ID) references GAZ_LOCATII(ID);
create index IDX_GAZ_VERIFICATOR_ON_ID_LOCATII on GAZ_VERIFICATOR (ID_LOCATII_ID);
