-- alter table GAZ_CONTRACTE_SERVICII_OE add column ID_CONTRACTE_RACORDARE_SD_ID uuid ^
-- update GAZ_CONTRACTE_SERVICII_OE set ID_CONTRACTE_RACORDARE_SD_ID = <default_value> ;
-- alter table GAZ_CONTRACTE_SERVICII_OE alter column ID_CONTRACTE_RACORDARE_SD_ID set not null ;
alter table GAZ_CONTRACTE_SERVICII_OE add column ID_CONTRACTE_RACORDARE_SD_ID uuid not null ;
alter table GAZ_CONTRACTE_SERVICII_OE add column PROC1_TARIF_PROIECTARE decimal(5, 2) ^
update GAZ_CONTRACTE_SERVICII_OE set PROC1_TARIF_PROIECTARE = 0 where PROC1_TARIF_PROIECTARE is null ;
alter table GAZ_CONTRACTE_SERVICII_OE alter column PROC1_TARIF_PROIECTARE set not null ;
alter table GAZ_CONTRACTE_SERVICII_OE add column TARIF1_PROIECTARE decimal(5, 2) ^
update GAZ_CONTRACTE_SERVICII_OE set TARIF1_PROIECTARE = 0 where TARIF1_PROIECTARE is null ;
alter table GAZ_CONTRACTE_SERVICII_OE alter column TARIF1_PROIECTARE set not null ;
alter table GAZ_CONTRACTE_SERVICII_OE add column PROC2_TARIF_PROIECTARE decimal(5, 2) ^
update GAZ_CONTRACTE_SERVICII_OE set PROC2_TARIF_PROIECTARE = 0 where PROC2_TARIF_PROIECTARE is null ;
alter table GAZ_CONTRACTE_SERVICII_OE alter column PROC2_TARIF_PROIECTARE set not null ;
alter table GAZ_CONTRACTE_SERVICII_OE add column TARIF2_PROIECTARE decimal(5, 2) ^
update GAZ_CONTRACTE_SERVICII_OE set TARIF2_PROIECTARE = 0 where TARIF2_PROIECTARE is null ;
alter table GAZ_CONTRACTE_SERVICII_OE alter column TARIF2_PROIECTARE set not null ;
alter table GAZ_CONTRACTE_SERVICII_OE add column PROC1_TARIF_VERIFICARE decimal(5, 2) ^
update GAZ_CONTRACTE_SERVICII_OE set PROC1_TARIF_VERIFICARE = 0 where PROC1_TARIF_VERIFICARE is null ;
alter table GAZ_CONTRACTE_SERVICII_OE alter column PROC1_TARIF_VERIFICARE set not null ;
alter table GAZ_CONTRACTE_SERVICII_OE add column TARIF1_VERIFICARE decimal(19, 2) ^
update GAZ_CONTRACTE_SERVICII_OE set TARIF1_VERIFICARE = 0 where TARIF1_VERIFICARE is null ;
alter table GAZ_CONTRACTE_SERVICII_OE alter column TARIF1_VERIFICARE set not null ;
alter table GAZ_CONTRACTE_SERVICII_OE add column PROC2_TARIF_VERIFICARE decimal(5, 2) ^
update GAZ_CONTRACTE_SERVICII_OE set PROC2_TARIF_VERIFICARE = 0 where PROC2_TARIF_VERIFICARE is null ;
alter table GAZ_CONTRACTE_SERVICII_OE alter column PROC2_TARIF_VERIFICARE set not null ;
alter table GAZ_CONTRACTE_SERVICII_OE add column TARIF2_VERIFICARE decimal(19, 2) ^
update GAZ_CONTRACTE_SERVICII_OE set TARIF2_VERIFICARE = 0 where TARIF2_VERIFICARE is null ;
alter table GAZ_CONTRACTE_SERVICII_OE alter column TARIF2_VERIFICARE set not null ;
alter table GAZ_CONTRACTE_SERVICII_OE add column PROC1_TARIF_EXECUTIE decimal(19, 2) ^
update GAZ_CONTRACTE_SERVICII_OE set PROC1_TARIF_EXECUTIE = 0 where PROC1_TARIF_EXECUTIE is null ;
alter table GAZ_CONTRACTE_SERVICII_OE alter column PROC1_TARIF_EXECUTIE set not null ;
alter table GAZ_CONTRACTE_SERVICII_OE add column TARIF1_EXECUTIE decimal(19, 2) ^
update GAZ_CONTRACTE_SERVICII_OE set TARIF1_EXECUTIE = 0 where TARIF1_EXECUTIE is null ;
alter table GAZ_CONTRACTE_SERVICII_OE alter column TARIF1_EXECUTIE set not null ;
alter table GAZ_CONTRACTE_SERVICII_OE add column PROC2_TARIF_EXECUTIE decimal(19, 2) ^
update GAZ_CONTRACTE_SERVICII_OE set PROC2_TARIF_EXECUTIE = 0 where PROC2_TARIF_EXECUTIE is null ;
alter table GAZ_CONTRACTE_SERVICII_OE alter column PROC2_TARIF_EXECUTIE set not null ;
alter table GAZ_CONTRACTE_SERVICII_OE add column TARIF2_EXECUTIE decimal(19, 2) ^
update GAZ_CONTRACTE_SERVICII_OE set TARIF2_EXECUTIE = 0 where TARIF2_EXECUTIE is null ;
alter table GAZ_CONTRACTE_SERVICII_OE alter column TARIF2_EXECUTIE set not null ;
