alter table GAZ_SOCIETATI_PROIECTARE add constraint FK_GAZ_SOCIETATI_PROIECTARE_ON_ID_FAX foreign key (ID_FAX_ID) references GAZ_TELEFOANE(ID);
create index IDX_GAZ_SOCIETATI_PROIECTARE_ON_ID_FAX on GAZ_SOCIETATI_PROIECTARE (ID_FAX_ID);
