create unique index IDX_GAZ_STATUS_CERERE_ATR_UK_NR_ORD on GAZ_STATUS_CERERE_ATR (NR_ORD) where DELETE_TS is null ;
create unique index IDX_GAZ_STATUS_CERERE_ATR_UK_STARE_CERERE_ATR on GAZ_STATUS_CERERE_ATR (STARE_CERERE_ATR) where DELETE_TS is null ;
