-- begin GAZ_ARTERA
create unique index IDX_GAZ_ARTERA_UK_TIP_ARTERA on GAZ_ARTERA (TIP_ARTERA) where DELETE_TS is null ^
-- end GAZ_ARTERA
-- begin GAZ_TARI
create unique index IDX_GAZ_TARI_UK_DENUMIRE_TARA on GAZ_TARI (DENUMIRE_TARA) where DELETE_TS is null ^
-- end GAZ_TARI
-- begin GAZ_JUDETE
create unique index IDX_GAZ_JUDETE_UK_NUME_JUDET on GAZ_JUDETE (NUME_JUDET) where DELETE_TS is null ^
-- end GAZ_JUDETE
-- begin GAZ_LOCALITATI
create unique index IDX_GAZ_LOCALITATI_UK_NUME_LOCALITATE on GAZ_LOCALITATI (NUME_LOCALITATE) where DELETE_TS is null ^
-- end GAZ_LOCALITATI
-- begin GAZ_STRAZI
create unique index IDX_GAZ_STRAZI_UK_NUME_STRADA on GAZ_STRAZI (NUME_STRADA) where DELETE_TS is null ^
-- end GAZ_STRAZI
-- begin GAZ_LOCATII
alter table GAZ_LOCATII add constraint FK_GAZ_LOCATII_ON_ID_PARTENERI foreign key (ID_PARTENERI_ID) references GAZ_PARTENERI(ID)^
alter table GAZ_LOCATII add constraint FK_GAZ_LOCATII_ON_ID_TARI foreign key (ID_TARI_ID) references GAZ_TARI(ID)^
alter table GAZ_LOCATII add constraint FK_GAZ_LOCATII_ON_ID_JUDETE foreign key (ID_JUDETE_ID) references GAZ_JUDETE(ID)^
alter table GAZ_LOCATII add constraint FK_GAZ_LOCATII_ON_ID_LOCALITATI foreign key (ID_LOCALITATI_ID) references GAZ_LOCALITATI(ID)^
alter table GAZ_LOCATII add constraint FK_GAZ_LOCATII_ON_ID_ARTERA foreign key (ID_ARTERA_ID) references GAZ_ARTERA(ID)^
alter table GAZ_LOCATII add constraint FK_GAZ_LOCATII_ON_ID_STRAZI foreign key (ID_STRAZI_ID) references GAZ_STRAZI(ID)^
create index IDX_GAZ_LOCATII_ON_ID_PARTENERI on GAZ_LOCATII (ID_PARTENERI_ID)^
create index IDX_GAZ_LOCATII_ON_ID_TARI on GAZ_LOCATII (ID_TARI_ID)^
create index IDX_GAZ_LOCATII_ON_ID_JUDETE on GAZ_LOCATII (ID_JUDETE_ID)^
create index IDX_GAZ_LOCATII_ON_ID_LOCALITATI on GAZ_LOCATII (ID_LOCALITATI_ID)^
create index IDX_GAZ_LOCATII_ON_ID_ARTERA on GAZ_LOCATII (ID_ARTERA_ID)^
create index IDX_GAZ_LOCATII_ON_ID_STRAZI on GAZ_LOCATII (ID_STRAZI_ID)^
-- end GAZ_LOCATII
-- begin GAZ_SIRUTA
create unique index IDX_GAZ_SIRUTA_UK_COD_SIRUTA on GAZ_SIRUTA (COD_SIRUTA) where DELETE_TS is null ^
-- end GAZ_SIRUTA
-- begin GAZ_ACORD_ACCES
alter table GAZ_ACORD_ACCES add constraint FK_GAZ_ACORD_ACCES_ON_ID_SIRUTA foreign key (ID_SIRUTA_ID) references GAZ_SIRUTA(ID)^
alter table GAZ_ACORD_ACCES add constraint FK_GAZ_ACORD_ACCES_ON_ID_PARTENERI foreign key (ID_PARTENERI_ID) references GAZ_PARTENERI(ID)^
alter table GAZ_ACORD_ACCES add constraint FK_GAZ_ACORD_ACCES_ON_ID_LOCATII foreign key (ID_LOCATII_ID) references GAZ_LOCATII(ID)^
alter table GAZ_ACORD_ACCES add constraint FK_GAZ_ACORD_ACCES_ON_ID_CONDUCTA foreign key (ID_CONDUCTA_ID) references GAZ_CONDUCTA(ID)^
create index IDX_GAZ_ACORD_ACCES_ON_ID_SIRUTA on GAZ_ACORD_ACCES (ID_SIRUTA_ID)^
create index IDX_GAZ_ACORD_ACCES_ON_ID_PARTENERI on GAZ_ACORD_ACCES (ID_PARTENERI_ID)^
create index IDX_GAZ_ACORD_ACCES_ON_ID_LOCATII on GAZ_ACORD_ACCES (ID_LOCATII_ID)^
create index IDX_GAZ_ACORD_ACCES_ON_ID_CONDUCTA on GAZ_ACORD_ACCES (ID_CONDUCTA_ID)^
-- end GAZ_ACORD_ACCES
-- begin GAZ_CERERI_RACORDARE
alter table GAZ_CERERI_RACORDARE add constraint FK_GAZ_CERERI_RACORDARE_ON_ID_PARTENER foreign key (ID_PARTENER_ID) references GAZ_PARTENERI(ID)^
alter table GAZ_CERERI_RACORDARE add constraint FK_GAZ_CERERI_RACORDARE_ON_LOCATIA_1 foreign key (LOCATIA_1_ID) references GAZ_LOCATII(ID)^
alter table GAZ_CERERI_RACORDARE add constraint FK_GAZ_CERERI_RACORDARE_ON_ID_CI_CIF_SOL foreign key (ID_CI_CIF_SOL_ID) references GAZ_CI_CIF(ID)^
alter table GAZ_CERERI_RACORDARE add constraint FK_GAZ_CERERI_RACORDARE_ON_ID_TELEFOANE_SOL foreign key (ID_TELEFOANE_SOL_ID) references GAZ_TELEFOANE(ID)^
alter table GAZ_CERERI_RACORDARE add constraint FK_GAZ_CERERI_RACORDARE_ON_ID_FAX_SOL foreign key (ID_FAX_SOL_ID) references GAZ_TELEFOANE(ID)^
alter table GAZ_CERERI_RACORDARE add constraint FK_GAZ_CERERI_RACORDARE_ON_ID_EMAIL_SOL foreign key (ID_EMAIL_SOL_ID) references GAZ_EMAIL(ID)^
alter table GAZ_CERERI_RACORDARE add constraint FK_GAZ_CERERI_RACORDARE_ON_ID_SIRUTA foreign key (ID_SIRUTA_ID) references GAZ_SIRUTA(ID)^
alter table GAZ_CERERI_RACORDARE add constraint FK_GAZ_CERERI_RACORDARE_ON_LOCATIA_2 foreign key (LOCATIA_2_ID) references GAZ_LOCATII(ID)^
alter table GAZ_CERERI_RACORDARE add constraint FK_GAZ_CERERI_RACORDARE_ON_LOCATIA_3 foreign key (LOCATIA_3_ID) references GAZ_LOCATII(ID)^
alter table GAZ_CERERI_RACORDARE add constraint FK_GAZ_CERERI_RACORDARE_ON_ID_MANDATAR foreign key (ID_MANDATAR_ID) references GAZ_PARTENERI(ID)^
alter table GAZ_CERERI_RACORDARE add constraint FK_GAZ_CERERI_RACORDARE_ON_ID_CI_CIF_MAN foreign key (ID_CI_CIF_MAN_ID) references GAZ_CI_CIF(ID)^
alter table GAZ_CERERI_RACORDARE add constraint FK_GAZ_CERERI_RACORDARE_ON_ID_TELEFOANE_MAN foreign key (ID_TELEFOANE_MAN_ID) references GAZ_TELEFOANE(ID)^
alter table GAZ_CERERI_RACORDARE add constraint FK_GAZ_CERERI_RACORDARE_ON_ID_FAX_MAN foreign key (ID_FAX_MAN_ID) references GAZ_TELEFOANE(ID)^
alter table GAZ_CERERI_RACORDARE add constraint FK_GAZ_CERERI_RACORDARE_ON_ID_EMAIL_MAN foreign key (ID_EMAIL_MAN_ID) references GAZ_EMAIL(ID)^
alter table GAZ_CERERI_RACORDARE add constraint FK_GAZ_CERERI_RACORDARE_ON_LOCATIA_4 foreign key (LOCATIA_4_ID) references GAZ_LOCATII(ID)^
alter table GAZ_CERERI_RACORDARE add constraint FK_GAZ_CERERI_RACORDARE_ON_ID_STATUS_CERERE_ATR foreign key (ID_STATUS_CERERE_ATR_ID) references GAZ_STATUS_CERERE_ATR(ID)^
create index IDX_GAZ_CERERI_RACORDARE_ON_ID_PARTENER on GAZ_CERERI_RACORDARE (ID_PARTENER_ID)^
create index IDX_GAZ_CERERI_RACORDARE_ON_LOCATIA_1 on GAZ_CERERI_RACORDARE (LOCATIA_1_ID)^
create index IDX_GAZ_CERERI_RACORDARE_ON_ID_CI_CIF_SOL on GAZ_CERERI_RACORDARE (ID_CI_CIF_SOL_ID)^
create index IDX_GAZ_CERERI_RACORDARE_ON_ID_TELEFOANE_SOL on GAZ_CERERI_RACORDARE (ID_TELEFOANE_SOL_ID)^
create index IDX_GAZ_CERERI_RACORDARE_ON_ID_FAX_SOL on GAZ_CERERI_RACORDARE (ID_FAX_SOL_ID)^
create index IDX_GAZ_CERERI_RACORDARE_ON_ID_EMAIL_SOL on GAZ_CERERI_RACORDARE (ID_EMAIL_SOL_ID)^
create index IDX_GAZ_CERERI_RACORDARE_ON_ID_SIRUTA on GAZ_CERERI_RACORDARE (ID_SIRUTA_ID)^
create index IDX_GAZ_CERERI_RACORDARE_ON_LOCATIA_2 on GAZ_CERERI_RACORDARE (LOCATIA_2_ID)^
create index IDX_GAZ_CERERI_RACORDARE_ON_LOCATIA_3 on GAZ_CERERI_RACORDARE (LOCATIA_3_ID)^
create index IDX_GAZ_CERERI_RACORDARE_ON_ID_MANDATAR on GAZ_CERERI_RACORDARE (ID_MANDATAR_ID)^
create index IDX_GAZ_CERERI_RACORDARE_ON_ID_CI_CIF_MAN on GAZ_CERERI_RACORDARE (ID_CI_CIF_MAN_ID)^
create index IDX_GAZ_CERERI_RACORDARE_ON_ID_TELEFOANE_MAN on GAZ_CERERI_RACORDARE (ID_TELEFOANE_MAN_ID)^
create index IDX_GAZ_CERERI_RACORDARE_ON_ID_FAX_MAN on GAZ_CERERI_RACORDARE (ID_FAX_MAN_ID)^
create index IDX_GAZ_CERERI_RACORDARE_ON_ID_EMAIL_MAN on GAZ_CERERI_RACORDARE (ID_EMAIL_MAN_ID)^
create index IDX_GAZ_CERERI_RACORDARE_ON_LOCATIA_4 on GAZ_CERERI_RACORDARE (LOCATIA_4_ID)^
create index IDX_GAZ_CERERI_RACORDARE_ON_ID_STATUS_CERERE_ATR on GAZ_CERERI_RACORDARE (ID_STATUS_CERERE_ATR_ID)^
-- end GAZ_CERERI_RACORDARE
-- begin GAZ_CI_CIF
alter table GAZ_CI_CIF add constraint FK_GAZ_CI_CIF_ON_ID_PARTENERI foreign key (ID_PARTENERI_ID) references GAZ_PARTENERI(ID)^
alter table GAZ_CI_CIF add constraint FK_GAZ_CI_CIF_ON_ID_TIP_ACT foreign key (ID_TIP_ACT_ID) references GAZ_TIP_ACT(ID)^
alter table GAZ_CI_CIF add constraint FK_GAZ_CI_CIF_ON_ID_INST_ELIB_ACTE foreign key (ID_INST_ELIB_ACTE_ID) references GAZ_INST_ELIB_ACTE(ID)^
create index IDX_GAZ_CI_CIF_ON_ID_PARTENERI on GAZ_CI_CIF (ID_PARTENERI_ID)^
create index IDX_GAZ_CI_CIF_ON_ID_TIP_ACT on GAZ_CI_CIF (ID_TIP_ACT_ID)^
create index IDX_GAZ_CI_CIF_ON_ID_INST_ELIB_ACTE on GAZ_CI_CIF (ID_INST_ELIB_ACTE_ID)^
-- end GAZ_CI_CIF
-- begin GAZ_TIP_ACT
create unique index IDX_GAZ_TIP_ACT_UK_TIP_ACT on GAZ_TIP_ACT (TIP_ACT) where DELETE_TS is null ^
-- end GAZ_TIP_ACT
-- begin GAZ_DIAM_OL
create unique index IDX_GAZ_DIAM_OL_UK_COD_SPECIFIC on GAZ_DIAM_OL (COD_SPECIFIC) where DELETE_TS is null ^
-- end GAZ_DIAM_OL
-- begin GAZ_DIAM_PE
create unique index IDX_GAZ_DIAM_PE_UK_DIAM_PE on GAZ_DIAM_PE (DIAM_PE) where DELETE_TS is null ^
-- end GAZ_DIAM_PE
-- begin GAZ_MAT_CONDUCTA
create unique index IDX_GAZ_MAT_CONDUCTA_UK_TIP_MAT_CONDUCTA on GAZ_MAT_CONDUCTA (TIP_MAT_CONDUCTA) where DELETE_TS is null ^
-- end GAZ_MAT_CONDUCTA
-- begin GAZ_OBIECTE
create unique index IDX_GAZ_OBIECTE_UK_TIP_OBIECTE on GAZ_OBIECTE (TIP_OBIECTE) where DELETE_TS is null ^
-- end GAZ_OBIECTE
-- begin GAZ_REGIM_PRES
create unique index IDX_GAZ_REGIM_PRES_UK_REGIM_PRESIUNE on GAZ_REGIM_PRES (REGIM_PRESIUNE) where DELETE_TS is null ^
-- end GAZ_REGIM_PRES
-- begin GAZ_TIP_TELEFON
create unique index IDX_GAZ_TIP_TELEFON_UK_DENUMIRE_TIP_TELEFON on GAZ_TIP_TELEFON (DENUMIRE_TIP_TELEFON) where DELETE_TS is null ^
-- end GAZ_TIP_TELEFON
-- begin GAZ_TELEFOANE
alter table GAZ_TELEFOANE add constraint FK_GAZ_TELEFOANE_ON_ID_PARTENERI foreign key (ID_PARTENERI_ID) references GAZ_PARTENERI(ID)^
alter table GAZ_TELEFOANE add constraint FK_GAZ_TELEFOANE_ON_ID_TIP_TELEFON foreign key (ID_TIP_TELEFON_ID) references GAZ_TIP_TELEFON(ID)^
create index IDX_GAZ_TELEFOANE_ON_ID_PARTENERI on GAZ_TELEFOANE (ID_PARTENERI_ID)^
create index IDX_GAZ_TELEFOANE_ON_ID_TIP_TELEFON on GAZ_TELEFOANE (ID_TIP_TELEFON_ID)^
-- end GAZ_TELEFOANE
-- begin GAZ_PROIECTE
alter table GAZ_PROIECTE add constraint FK_GAZ_PROIECTE_ON_ID_OBIECTE foreign key (ID_OBIECTE_ID) references GAZ_OBIECTE(ID)^
alter table GAZ_PROIECTE add constraint FK_GAZ_PROIECTE_ON_ID_PROIECTANT foreign key (ID_PROIECTANT_ID) references GAZ_PROIECTANT(ID)^
alter table GAZ_PROIECTE add constraint FK_GAZ_PROIECTE_ON_ID_VERIFICATOR foreign key (ID_VERIFICATOR_ID) references GAZ_VERIFICATOR(ID)^
create index IDX_GAZ_PROIECTE_ON_ID_OBIECTE on GAZ_PROIECTE (ID_OBIECTE_ID)^
create index IDX_GAZ_PROIECTE_ON_ID_PROIECTANT on GAZ_PROIECTE (ID_PROIECTANT_ID)^
create index IDX_GAZ_PROIECTE_ON_ID_VERIFICATOR on GAZ_PROIECTE (ID_VERIFICATOR_ID)^
-- end GAZ_PROIECTE
-- begin GAZ_INST_UTILIZARE
alter table GAZ_INST_UTILIZARE add constraint FK_GAZ_INST_UTILIZARE_ON_ID_SIRUTA foreign key (ID_SIRUTA_ID) references GAZ_SIRUTA(ID)^
alter table GAZ_INST_UTILIZARE add constraint FK_GAZ_INST_UTILIZARE_ON_ID_LOCATII foreign key (ID_LOCATII_ID) references GAZ_LOCATII(ID)^
alter table GAZ_INST_UTILIZARE add constraint FK_GAZ_INST_UTILIZARE_ON_ID_SRMPRM foreign key (ID_SRMPRM_ID) references GAZ_SRMPRM(ID)^
alter table GAZ_INST_UTILIZARE add constraint FK_GAZ_INST_UTILIZARE_ON_ID_PROIECTE foreign key (ID_PROIECTE_ID) references GAZ_PROIECTE(ID)^
alter table GAZ_INST_UTILIZARE add constraint FK_GAZ_INST_UTILIZARE_ON_ID_EXECUTANT foreign key (ID_EXECUTANT_ID) references GAZ_EXECUTANT(ID)^
create index IDX_GAZ_INST_UTILIZARE_ON_ID_SIRUTA on GAZ_INST_UTILIZARE (ID_SIRUTA_ID)^
create index IDX_GAZ_INST_UTILIZARE_ON_ID_LOCATII on GAZ_INST_UTILIZARE (ID_LOCATII_ID)^
create index IDX_GAZ_INST_UTILIZARE_ON_ID_SRMPRM on GAZ_INST_UTILIZARE (ID_SRMPRM_ID)^
create index IDX_GAZ_INST_UTILIZARE_ON_ID_PROIECTE on GAZ_INST_UTILIZARE (ID_PROIECTE_ID)^
create index IDX_GAZ_INST_UTILIZARE_ON_ID_EXECUTANT on GAZ_INST_UTILIZARE (ID_EXECUTANT_ID)^
-- end GAZ_INST_UTILIZARE
-- begin GAZ_SRMPRM
alter table GAZ_SRMPRM add constraint FK_GAZ_SRMPRM_ON_ID_SIRUTA foreign key (ID_SIRUTA_ID) references GAZ_SIRUTA(ID)^
alter table GAZ_SRMPRM add constraint FK_GAZ_SRMPRM_ON_ID_BRANSAMENTE foreign key (ID_BRANSAMENTE_ID) references GAZ_BRANSAMENTE(ID)^
alter table GAZ_SRMPRM add constraint FK_GAZ_SRMPRM_ON_ID_LOCATII foreign key (ID_LOCATII_ID) references GAZ_LOCATII(ID)^
alter table GAZ_SRMPRM add constraint FK_GAZ_SRMPRM_ON_ID_PROIECTE foreign key (ID_PROIECTE_ID) references GAZ_PROIECTE(ID)^
alter table GAZ_SRMPRM add constraint FK_GAZ_SRMPRM_ON_ID_EXECUTANT foreign key (ID_EXECUTANT_ID) references GAZ_EXECUTANT(ID)^
alter table GAZ_SRMPRM add constraint FK_GAZ_SRMPRM_ON_ID_REGIM_PRES foreign key (ID_REGIM_PRES_ID) references GAZ_REGIM_PRES(ID)^
create index IDX_GAZ_SRMPRM_ON_ID_SIRUTA on GAZ_SRMPRM (ID_SIRUTA_ID)^
create index IDX_GAZ_SRMPRM_ON_ID_BRANSAMENTE on GAZ_SRMPRM (ID_BRANSAMENTE_ID)^
create index IDX_GAZ_SRMPRM_ON_ID_LOCATII on GAZ_SRMPRM (ID_LOCATII_ID)^
create index IDX_GAZ_SRMPRM_ON_ID_PROIECTE on GAZ_SRMPRM (ID_PROIECTE_ID)^
create index IDX_GAZ_SRMPRM_ON_ID_EXECUTANT on GAZ_SRMPRM (ID_EXECUTANT_ID)^
create index IDX_GAZ_SRMPRM_ON_ID_REGIM_PRES on GAZ_SRMPRM (ID_REGIM_PRES_ID)^
-- end GAZ_SRMPRM
-- begin GAZ_BRANSAMENTE
alter table GAZ_BRANSAMENTE add constraint FK_GAZ_BRANSAMENTE_ON_ID_SIRUTA foreign key (ID_SIRUTA_ID) references GAZ_SIRUTA(ID)^
alter table GAZ_BRANSAMENTE add constraint FK_GAZ_BRANSAMENTE_ON_ID_LOCATII foreign key (ID_LOCATII_ID) references GAZ_LOCATII(ID)^
alter table GAZ_BRANSAMENTE add constraint FK_GAZ_BRANSAMENTE_ON_ID_REGIM_PRES foreign key (ID_REGIM_PRES_ID) references GAZ_REGIM_PRES(ID)^
alter table GAZ_BRANSAMENTE add constraint FK_GAZ_BRANSAMENTE_ON_ID_MAT_CONDUCTA_PE foreign key (ID_MAT_CONDUCTA_PE_ID) references GAZ_MAT_CONDUCTA(ID)^
alter table GAZ_BRANSAMENTE add constraint FK_GAZ_BRANSAMENTE_ON_ID_DIAM_PE foreign key (ID_DIAM_PE_ID) references GAZ_DIAM_PE(ID)^
alter table GAZ_BRANSAMENTE add constraint FK_GAZ_BRANSAMENTE_ON_ID_MAT_CONDUCTA_OL foreign key (ID_MAT_CONDUCTA_OL_ID) references GAZ_MAT_CONDUCTA(ID)^
alter table GAZ_BRANSAMENTE add constraint FK_GAZ_BRANSAMENTE_ON_ID_DIAM_OL foreign key (ID_DIAM_OL_ID) references GAZ_DIAM_OL(ID)^
alter table GAZ_BRANSAMENTE add constraint FK_GAZ_BRANSAMENTE_ON_ID_EXECUTANT foreign key (ID_EXECUTANT_ID) references GAZ_EXECUTANT(ID)^
alter table GAZ_BRANSAMENTE add constraint FK_GAZ_BRANSAMENTE_ON_ID_PROIECTE foreign key (ID_PROIECTE_ID) references GAZ_PROIECTE(ID)^
create index IDX_GAZ_BRANSAMENTE_ON_ID_SIRUTA on GAZ_BRANSAMENTE (ID_SIRUTA_ID)^
create index IDX_GAZ_BRANSAMENTE_ON_ID_LOCATII on GAZ_BRANSAMENTE (ID_LOCATII_ID)^
create index IDX_GAZ_BRANSAMENTE_ON_ID_REGIM_PRES on GAZ_BRANSAMENTE (ID_REGIM_PRES_ID)^
create index IDX_GAZ_BRANSAMENTE_ON_ID_MAT_CONDUCTA_PE on GAZ_BRANSAMENTE (ID_MAT_CONDUCTA_PE_ID)^
create index IDX_GAZ_BRANSAMENTE_ON_ID_DIAM_PE on GAZ_BRANSAMENTE (ID_DIAM_PE_ID)^
create index IDX_GAZ_BRANSAMENTE_ON_ID_MAT_CONDUCTA_OL on GAZ_BRANSAMENTE (ID_MAT_CONDUCTA_OL_ID)^
create index IDX_GAZ_BRANSAMENTE_ON_ID_DIAM_OL on GAZ_BRANSAMENTE (ID_DIAM_OL_ID)^
create index IDX_GAZ_BRANSAMENTE_ON_ID_EXECUTANT on GAZ_BRANSAMENTE (ID_EXECUTANT_ID)^
create index IDX_GAZ_BRANSAMENTE_ON_ID_PROIECTE on GAZ_BRANSAMENTE (ID_PROIECTE_ID)^
-- end GAZ_BRANSAMENTE
-- begin GAZ_ACORD_TEHNIC_RACORDARE
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_SIRUTA foreign key (ID_SIRUTA_ID) references GAZ_SIRUTA(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_TIP_ARTERA foreign key (ID_TIP_ARTERA_ID) references GAZ_ARTERA(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_STRAZI foreign key (ID_STRAZI_ID) references GAZ_STRAZI(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_CERERI_RACORDARE foreign key (ID_CERERI_RACORDARE_ID) references GAZ_CERERI_RACORDARE(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_CONDUCTA_RACORD foreign key (ID_CONDUCTA_RACORD_ID) references GAZ_CONDUCTA(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_MAT_CONDUCTA_RACORD_OL foreign key (ID_MAT_CONDUCTA_RACORD_OL_ID) references GAZ_MAT_CONDUCTA(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_DIAM_OL_RACORD foreign key (ID_DIAM_OL_RACORD_ID) references GAZ_DIAM_OL(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_MAT_CONDUCTA_RACORD_PE foreign key (ID_MAT_CONDUCTA_RACORD_PE_ID) references GAZ_MAT_CONDUCTA(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_DIAM_PE_RACORD foreign key (ID_DIAM_PE_RACORD_ID) references GAZ_DIAM_PE(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_MAT_CONDUCTA_RACORD_PE2 foreign key (ID_MAT_CONDUCTA_RACORD_PE2_ID) references GAZ_MAT_CONDUCTA(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_DIAM_PE_RACORD2 foreign key (ID_DIAM_PE_RACORD2_ID) references GAZ_DIAM_PE(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_CONDUCTA_EXTINDERE foreign key (ID_CONDUCTA_EXTINDERE_ID) references GAZ_CONDUCTA(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORDTEHNICRACORD_ON_ID_CONDUCTA_EXTINDERE_EXISTENTA foreign key (ID_CONDUCTA_EXTINDERE_EXISTENTA_ID) references GAZ_CONDUCTA(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_MAT_CONDUCTA_EXTINDERE_OL foreign key (ID_MAT_CONDUCTA_EXTINDERE_OL_ID) references GAZ_MAT_CONDUCTA(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_DIAM_OL_EXTINDERE foreign key (ID_DIAM_OL_EXTINDERE_ID) references GAZ_DIAM_OL(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_MAT_CONDUCTA_EXTINDERE_PE foreign key (ID_MAT_CONDUCTA_EXTINDERE_PE_ID) references GAZ_MAT_CONDUCTA(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_DIAM_PE_EXTINDERE foreign key (ID_DIAM_PE_EXTINDERE_ID) references GAZ_DIAM_PE(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_CONDUCTA_REDIMENSIONARE foreign key (ID_CONDUCTA_REDIMENSIONARE_ID) references GAZ_CONDUCTA(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORDTEHNICRACORD_ON_IDCONDUCREDIMEEXISTE foreign key (ID_CONDUCTA_REDIMENSIONARE_EXISTENTA_ID) references GAZ_CONDUCTA(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORDTEHNIRACOR_ON_ID_MAT_CONDUCTA_REDIMENSIONARE_PE foreign key (ID_MAT_CONDUCTA_REDIMENSIONARE_PE_ID) references GAZ_MAT_CONDUCTA(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_DIAM_OL_REDIMENSIONARE foreign key (ID_DIAM_OL_REDIMENSIONARE_ID) references GAZ_DIAM_OL(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORDTEHNIRACOR_ON_ID_MAT_CONDUCTA_REDIMENSIONARE_OL foreign key (ID_MAT_CONDUCTA_REDIMENSIONARE_OL_ID) references GAZ_MAT_CONDUCTA(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_DIAM_PE_REDIMENSIONARE foreign key (ID_DIAM_PE_REDIMENSIONARE_ID) references GAZ_DIAM_PE(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_OBIECTE_BR foreign key (ID_OBIECTE_BR_ID) references GAZ_OBIECTE(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_OBIECTE_POST foreign key (ID_OBIECTE_POST_ID) references GAZ_OBIECTE(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_TIP_CONTOR foreign key (ID_TIP_CONTOR_ID) references GAZ_TIP_CONTOR(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_TIP_REGULATOR foreign key (ID_TIP_REGULATOR_ID) references GAZ_TIP_REGULATOR(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_IMAGINE_SOLUTIE foreign key (IMAGINE_SOLUTIE_ID) references SYS_FILE(ID)^
alter table GAZ_ACORD_TEHNIC_RACORDARE add constraint FK_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_INSTALATORI_OSD foreign key (ID_INSTALATORI_OSD_ID) references GAZ_INSTALATORI_OSD(ID)^
create unique index IDX_GAZ_ACORD_TEHNIC_RACORDARE_UK_ID_CERERI_RACORDARE_ID on GAZ_ACORD_TEHNIC_RACORDARE (ID_CERERI_RACORDARE_ID) where DELETE_TS is null ^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_SIRUTA on GAZ_ACORD_TEHNIC_RACORDARE (ID_SIRUTA_ID)^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_TIP_ARTERA on GAZ_ACORD_TEHNIC_RACORDARE (ID_TIP_ARTERA_ID)^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_STRAZI on GAZ_ACORD_TEHNIC_RACORDARE (ID_STRAZI_ID)^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_CERERI_RACORDARE on GAZ_ACORD_TEHNIC_RACORDARE (ID_CERERI_RACORDARE_ID)^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_CONDUCTA_RACORD on GAZ_ACORD_TEHNIC_RACORDARE (ID_CONDUCTA_RACORD_ID)^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_MAT_CONDUCTA_RACORD_OL on GAZ_ACORD_TEHNIC_RACORDARE (ID_MAT_CONDUCTA_RACORD_OL_ID)^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_DIAM_OL_RACORD on GAZ_ACORD_TEHNIC_RACORDARE (ID_DIAM_OL_RACORD_ID)^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_MAT_CONDUCTA_RACORD_PE on GAZ_ACORD_TEHNIC_RACORDARE (ID_MAT_CONDUCTA_RACORD_PE_ID)^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_DIAM_PE_RACORD on GAZ_ACORD_TEHNIC_RACORDARE (ID_DIAM_PE_RACORD_ID)^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_MAT_CONDUCTA_RACORD_PE2 on GAZ_ACORD_TEHNIC_RACORDARE (ID_MAT_CONDUCTA_RACORD_PE2_ID)^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_DIAM_PE_RACORD2 on GAZ_ACORD_TEHNIC_RACORDARE (ID_DIAM_PE_RACORD2_ID)^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_CONDUCTA_EXTINDERE on GAZ_ACORD_TEHNIC_RACORDARE (ID_CONDUCTA_EXTINDERE_ID)^
create index IDX_GAZ_ACORDTEHNICRACORD_ON_ID_CONDUCTA_EXTINDERE_EXISTENTA on GAZ_ACORD_TEHNIC_RACORDARE (ID_CONDUCTA_EXTINDERE_EXISTENTA_ID)^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_MAT_CONDUCTA_EXTINDERE_OL on GAZ_ACORD_TEHNIC_RACORDARE (ID_MAT_CONDUCTA_EXTINDERE_OL_ID)^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_DIAM_OL_EXTINDERE on GAZ_ACORD_TEHNIC_RACORDARE (ID_DIAM_OL_EXTINDERE_ID)^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_MAT_CONDUCTA_EXTINDERE_PE on GAZ_ACORD_TEHNIC_RACORDARE (ID_MAT_CONDUCTA_EXTINDERE_PE_ID)^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_DIAM_PE_EXTINDERE on GAZ_ACORD_TEHNIC_RACORDARE (ID_DIAM_PE_EXTINDERE_ID)^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_CONDUCTA_REDIMENSIONARE on GAZ_ACORD_TEHNIC_RACORDARE (ID_CONDUCTA_REDIMENSIONARE_ID)^
create index IDX_GAZ_ACORDTEHNICRACORD_ON_IDCONDUCREDIMEEXISTE on GAZ_ACORD_TEHNIC_RACORDARE (ID_CONDUCTA_REDIMENSIONARE_EXISTENTA_ID)^
create index IDX_GAZ_ACORDTEHNIRACOR_ON_ID_MAT_CONDUCTA_REDIMENSIONARE_PE on GAZ_ACORD_TEHNIC_RACORDARE (ID_MAT_CONDUCTA_REDIMENSIONARE_PE_ID)^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_DIAM_OL_REDIMENSIONARE on GAZ_ACORD_TEHNIC_RACORDARE (ID_DIAM_OL_REDIMENSIONARE_ID)^
create index IDX_GAZ_ACORDTEHNIRACOR_ON_ID_MAT_CONDUCTA_REDIMENSIONARE_OL on GAZ_ACORD_TEHNIC_RACORDARE (ID_MAT_CONDUCTA_REDIMENSIONARE_OL_ID)^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_DIAM_PE_REDIMENSIONARE on GAZ_ACORD_TEHNIC_RACORDARE (ID_DIAM_PE_REDIMENSIONARE_ID)^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_OBIECTE_BR on GAZ_ACORD_TEHNIC_RACORDARE (ID_OBIECTE_BR_ID)^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_OBIECTE_POST on GAZ_ACORD_TEHNIC_RACORDARE (ID_OBIECTE_POST_ID)^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_TIP_CONTOR on GAZ_ACORD_TEHNIC_RACORDARE (ID_TIP_CONTOR_ID)^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_TIP_REGULATOR on GAZ_ACORD_TEHNIC_RACORDARE (ID_TIP_REGULATOR_ID)^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_IMAGINE_SOLUTIE on GAZ_ACORD_TEHNIC_RACORDARE (IMAGINE_SOLUTIE_ID)^
create index IDX_GAZ_ACORD_TEHNIC_RACORDARE_ON_ID_INSTALATORI_OSD on GAZ_ACORD_TEHNIC_RACORDARE (ID_INSTALATORI_OSD_ID)^
-- end GAZ_ACORD_TEHNIC_RACORDARE
-- begin GAZ_CONDUCTA
alter table GAZ_CONDUCTA add constraint FK_GAZ_CONDUCTA_ON_ID_SIRUTA foreign key (ID_SIRUTA_ID) references GAZ_SIRUTA(ID)^
alter table GAZ_CONDUCTA add constraint FK_GAZ_CONDUCTA_ON_ID_ARTERA_NOD1 foreign key (ID_ARTERA_NOD1_ID) references GAZ_ARTERA(ID)^
alter table GAZ_CONDUCTA add constraint FK_GAZ_CONDUCTA_ON_ID_STRAZI_NOD1 foreign key (ID_STRAZI_NOD1_ID) references GAZ_STRAZI(ID)^
alter table GAZ_CONDUCTA add constraint FK_GAZ_CONDUCTA_ON_ID_ARTERA_NOD2 foreign key (ID_ARTERA_NOD2_ID) references GAZ_ARTERA(ID)^
alter table GAZ_CONDUCTA add constraint FK_GAZ_CONDUCTA_ON_ID_STRAZI_NOD2 foreign key (ID_STRAZI_NOD2_ID) references GAZ_STRAZI(ID)^
alter table GAZ_CONDUCTA add constraint FK_GAZ_CONDUCTA_ON_ID_MAT_CONDUCTA_PE foreign key (ID_MAT_CONDUCTA_PE_ID) references GAZ_MAT_CONDUCTA(ID)^
alter table GAZ_CONDUCTA add constraint FK_GAZ_CONDUCTA_ON_ID_DIAM_PE foreign key (ID_DIAM_PE_ID) references GAZ_DIAM_PE(ID)^
alter table GAZ_CONDUCTA add constraint FK_GAZ_CONDUCTA_ON_ID_MAT_CONDUCTA_OL foreign key (ID_MAT_CONDUCTA_OL_ID) references GAZ_MAT_CONDUCTA(ID)^
alter table GAZ_CONDUCTA add constraint FK_GAZ_CONDUCTA_ON_ID_DIAM_OL foreign key (ID_DIAM_OL_ID) references GAZ_DIAM_OL(ID)^
alter table GAZ_CONDUCTA add constraint FK_GAZ_CONDUCTA_ON_ID_REGIM_PRES foreign key (ID_REGIM_PRES_ID) references GAZ_REGIM_PRES(ID)^
alter table GAZ_CONDUCTA add constraint FK_GAZ_CONDUCTA_ON_ID_SRS foreign key (ID_SRS_ID) references GAZ_SRS(ID)^
create index IDX_GAZ_CONDUCTA_ON_ID_SIRUTA on GAZ_CONDUCTA (ID_SIRUTA_ID)^
create index IDX_GAZ_CONDUCTA_ON_ID_ARTERA_NOD1 on GAZ_CONDUCTA (ID_ARTERA_NOD1_ID)^
create index IDX_GAZ_CONDUCTA_ON_ID_STRAZI_NOD1 on GAZ_CONDUCTA (ID_STRAZI_NOD1_ID)^
create index IDX_GAZ_CONDUCTA_ON_ID_ARTERA_NOD2 on GAZ_CONDUCTA (ID_ARTERA_NOD2_ID)^
create index IDX_GAZ_CONDUCTA_ON_ID_STRAZI_NOD2 on GAZ_CONDUCTA (ID_STRAZI_NOD2_ID)^
create index IDX_GAZ_CONDUCTA_ON_ID_MAT_CONDUCTA_PE on GAZ_CONDUCTA (ID_MAT_CONDUCTA_PE_ID)^
create index IDX_GAZ_CONDUCTA_ON_ID_DIAM_PE on GAZ_CONDUCTA (ID_DIAM_PE_ID)^
create index IDX_GAZ_CONDUCTA_ON_ID_MAT_CONDUCTA_OL on GAZ_CONDUCTA (ID_MAT_CONDUCTA_OL_ID)^
create index IDX_GAZ_CONDUCTA_ON_ID_DIAM_OL on GAZ_CONDUCTA (ID_DIAM_OL_ID)^
create index IDX_GAZ_CONDUCTA_ON_ID_REGIM_PRES on GAZ_CONDUCTA (ID_REGIM_PRES_ID)^
create index IDX_GAZ_CONDUCTA_ON_ID_SRS on GAZ_CONDUCTA (ID_SRS_ID)^
-- end GAZ_CONDUCTA
-- begin GAZ_EMAIL
alter table GAZ_EMAIL add constraint FK_GAZ_EMAIL_ON_ID_PARTENERI foreign key (ID_PARTENERI_ID) references GAZ_PARTENERI(ID)^
create index IDX_GAZ_EMAIL_ON_ID_PARTENERI on GAZ_EMAIL (ID_PARTENERI_ID)^
-- end GAZ_EMAIL

-- begin GAZ_APARATE_SOLICITATE
alter table GAZ_APARATE_SOLICITATE add constraint FK_GAZ_APARATE_SOLICITATE_ON_ID_CERERI_RACORDARE foreign key (ID_CERERI_RACORDARE_ID) references GAZ_CERERI_RACORDARE(ID)^
alter table GAZ_APARATE_SOLICITATE add constraint FK_GAZ_APARATE_SOLICITATE_ON_ID_APARATE foreign key (ID_APARATE_ID) references GAZ_TIP_APARATE(ID)^
create index IDX_GAZ_APARATE_SOLICITATE_ON_ID_CERERI_RACORDARE on GAZ_APARATE_SOLICITATE (ID_CERERI_RACORDARE_ID)^
create index IDX_GAZ_APARATE_SOLICITATE_ON_ID_APARATE on GAZ_APARATE_SOLICITATE (ID_APARATE_ID)^
-- end GAZ_APARATE_SOLICITATE
-- begin GAZ_DOC_ANEX_CER_RAC
alter table GAZ_DOC_ANEX_CER_RAC add constraint FK_GAZ_DOC_ANEX_CER_RAC_ON_ID_CERERI_RACORDARE foreign key (ID_CERERI_RACORDARE_ID) references GAZ_CERERI_RACORDARE(ID)^
alter table GAZ_DOC_ANEX_CER_RAC add constraint FK_GAZ_DOC_ANEX_CER_RAC_ON_ID_TIP_DOCUMENTE foreign key (ID_TIP_DOCUMENTE_ID) references GAZ_TIP_DOCUMENTE(ID)^
alter table GAZ_DOC_ANEX_CER_RAC add constraint FK_GAZ_DOC_ANEX_CER_RAC_ON_FISIER_DOCUMENT foreign key (FISIER_DOCUMENT_ID) references SYS_FILE(ID)^
create index IDX_GAZ_DOC_ANEX_CER_RAC_ON_ID_CERERI_RACORDARE on GAZ_DOC_ANEX_CER_RAC (ID_CERERI_RACORDARE_ID)^
create index IDX_GAZ_DOC_ANEX_CER_RAC_ON_ID_TIP_DOCUMENTE on GAZ_DOC_ANEX_CER_RAC (ID_TIP_DOCUMENTE_ID)^
create index IDX_GAZ_DOC_ANEX_CER_RAC_ON_FISIER_DOCUMENT on GAZ_DOC_ANEX_CER_RAC (FISIER_DOCUMENT_ID)^
-- end GAZ_DOC_ANEX_CER_RAC
-- begin GAZ_CONTRACTE_RACORDARE_SD
alter table GAZ_CONTRACTE_RACORDARE_SD add constraint FK_GAZ_CONTRACTE_RACORDARE_SD_ON_ID_SIRUTA foreign key (ID_SIRUTA_ID) references GAZ_SIRUTA(ID)^
alter table GAZ_CONTRACTE_RACORDARE_SD add constraint FK_GAZ_CONTRACTE_RACORDARE_SD_ON_ID_PARTENERI foreign key (ID_PARTENERI_ID) references GAZ_PARTENERI(ID)^
alter table GAZ_CONTRACTE_RACORDARE_SD add constraint FK_GAZ_CONTRACTE_RACORDARE_SD_ON_ID_CI_CIF foreign key (ID_CI_CIF_ID) references GAZ_CI_CIF(ID)^
alter table GAZ_CONTRACTE_RACORDARE_SD add constraint FK_GAZ_CONTRACTE_RACORDARE_SD_ON_LOCATIA_1 foreign key (LOCATIA_1_ID) references GAZ_LOCATII(ID)^
alter table GAZ_CONTRACTE_RACORDARE_SD add constraint FK_GAZ_CONTRACTE_RACORDARE_SD_ON_ID_TELEFOANE foreign key (ID_TELEFOANE_ID) references GAZ_TELEFOANE(ID)^
alter table GAZ_CONTRACTE_RACORDARE_SD add constraint FK_GAZ_CONTRACTE_RACORDARE_SD_ON_ID_FAX foreign key (ID_FAX_ID) references GAZ_TELEFOANE(ID)^
alter table GAZ_CONTRACTE_RACORDARE_SD add constraint FK_GAZ_CONTRACTE_RACORDARE_SD_ON_ID_EMAIL foreign key (ID_EMAIL_ID) references GAZ_EMAIL(ID)^
alter table GAZ_CONTRACTE_RACORDARE_SD add constraint FK_GAZ_CONTRACTE_RACORDARE_SD_ON_ID_CONTURI_BANCARE_PARTENERI foreign key (ID_CONTURI_BANCARE_PARTENERI_ID) references GAZ_CONTURI_BANCARE_PARTENERI(ID)^
alter table GAZ_CONTRACTE_RACORDARE_SD add constraint FK_GAZ_CONTRACTE_RACORDARE_SD_ON_ID_ACORD_TEHNIC_RACORDARE foreign key (ID_ACORD_TEHNIC_RACORDARE_ID) references GAZ_ACORD_TEHNIC_RACORDARE(ID)^
alter table GAZ_CONTRACTE_RACORDARE_SD add constraint FK_GAZ_CONTRACTE_RACORDARE_SD_ON_LOCATIA_2 foreign key (LOCATIA_2_ID) references GAZ_LOCATII(ID)^
alter table GAZ_CONTRACTE_RACORDARE_SD add constraint FK_GAZ_CONTRACTE_RACORDARE_SD_ON_ID_NOTIFICARE_OSD_ATR foreign key (ID_NOTIFICARE_OSD_ATR_ID) references GAZ_NOTIFICARE_OSD_ATR(ID)^
alter table GAZ_CONTRACTE_RACORDARE_SD add constraint FK_GAZ_CONTRRACORSD_ON_ID_STATUS_CONTRACTE_RACORDARE_SD1 foreign key (ID_STATUS_CONTRACTE_RACORDARE_SD_ID) references GAZ_STATUS_CONTRACTE_RACORDARE_SD(ID)^
create index IDX_GAZ_CONTRACTE_RACORDARE_SD_ON_ID_SIRUTA on GAZ_CONTRACTE_RACORDARE_SD (ID_SIRUTA_ID)^
create index IDX_GAZ_CONTRACTE_RACORDARE_SD_ON_ID_PARTENERI on GAZ_CONTRACTE_RACORDARE_SD (ID_PARTENERI_ID)^
create index IDX_GAZ_CONTRACTE_RACORDARE_SD_ON_ID_CI_CIF on GAZ_CONTRACTE_RACORDARE_SD (ID_CI_CIF_ID)^
create index IDX_GAZ_CONTRACTE_RACORDARE_SD_ON_LOCATIA_1 on GAZ_CONTRACTE_RACORDARE_SD (LOCATIA_1_ID)^
create index IDX_GAZ_CONTRACTE_RACORDARE_SD_ON_ID_TELEFOANE on GAZ_CONTRACTE_RACORDARE_SD (ID_TELEFOANE_ID)^
create index IDX_GAZ_CONTRACTE_RACORDARE_SD_ON_ID_FAX on GAZ_CONTRACTE_RACORDARE_SD (ID_FAX_ID)^
create index IDX_GAZ_CONTRACTE_RACORDARE_SD_ON_ID_EMAIL on GAZ_CONTRACTE_RACORDARE_SD (ID_EMAIL_ID)^
create index IDX_GAZ_CONTRACTE_RACORDARE_SD_ON_ID_CONTURI_BANCARE_PARTENERI on GAZ_CONTRACTE_RACORDARE_SD (ID_CONTURI_BANCARE_PARTENERI_ID)^
create index IDX_GAZ_CONTRACTE_RACORDARE_SD_ON_ID_ACORD_TEHNIC_RACORDARE on GAZ_CONTRACTE_RACORDARE_SD (ID_ACORD_TEHNIC_RACORDARE_ID)^
create index IDX_GAZ_CONTRACTE_RACORDARE_SD_ON_LOCATIA_2 on GAZ_CONTRACTE_RACORDARE_SD (LOCATIA_2_ID)^
create index IDX_GAZ_CONTRACTE_RACORDARE_SD_ON_ID_NOTIFICARE_OSD_ATR on GAZ_CONTRACTE_RACORDARE_SD (ID_NOTIFICARE_OSD_ATR_ID)^
create index IDX_GAZ_CONTRRACORSD_ON_ID_STATUS_CONTRACTE_RACORDARE_SD1 on GAZ_CONTRACTE_RACORDARE_SD (ID_STATUS_CONTRACTE_RACORDARE_SD_ID)^
-- end GAZ_CONTRACTE_RACORDARE_SD
-- begin GAZ_PARTENERI
alter table GAZ_PARTENERI add constraint FK_GAZ_PARTENERI_ON_ID_TIP_PERSOANA foreign key (ID_TIP_PERSOANA_ID) references GAZ_TIP_PERSOANA(ID)^
create index IDX_GAZ_PARTENERI_ON_ID_TIP_PERSOANA on GAZ_PARTENERI (ID_TIP_PERSOANA_ID)^
-- end GAZ_PARTENERI
-- begin GAZ_NOTIFICARE_OSD_ATR
alter table GAZ_NOTIFICARE_OSD_ATR add constraint FK_GAZ_NOTIFICARE_OSD_ATR_ON_ID_SIRUTA foreign key (ID_SIRUTA_ID) references GAZ_SIRUTA(ID)^
alter table GAZ_NOTIFICARE_OSD_ATR add constraint FK_GAZ_NOTIFICARE_OSD_ATR_ON_ID_PARTENERI foreign key (ID_PARTENERI_ID) references GAZ_PARTENERI(ID)^
alter table GAZ_NOTIFICARE_OSD_ATR add constraint FK_GAZ_NOTIFICARE_OSD_ATR_ON_ID_CI_CIF foreign key (ID_CI_CIF_ID) references GAZ_CI_CIF(ID)^
alter table GAZ_NOTIFICARE_OSD_ATR add constraint FK_GAZ_NOTIFICARE_OSD_ATR_ON_LOCATIA_1 foreign key (LOCATIA_1_ID) references GAZ_LOCATII(ID)^
alter table GAZ_NOTIFICARE_OSD_ATR add constraint FK_GAZ_NOTIFICARE_OSD_ATR_ON_ID_TELEFOANE foreign key (ID_TELEFOANE_ID) references GAZ_TELEFOANE(ID)^
alter table GAZ_NOTIFICARE_OSD_ATR add constraint FK_GAZ_NOTIFICARE_OSD_ATR_ON_ID_FAX foreign key (ID_FAX_ID) references GAZ_TELEFOANE(ID)^
alter table GAZ_NOTIFICARE_OSD_ATR add constraint FK_GAZ_NOTIFICARE_OSD_ATR_ON_ID_EMAIL foreign key (ID_EMAIL_ID) references GAZ_EMAIL(ID)^
alter table GAZ_NOTIFICARE_OSD_ATR add constraint FK_GAZ_NOTIFICARE_OSD_ATR_ON_ID_ACORD_TEHNIC_RACORDARE foreign key (ID_ACORD_TEHNIC_RACORDARE_ID) references GAZ_ACORD_TEHNIC_RACORDARE(ID)^
alter table GAZ_NOTIFICARE_OSD_ATR add constraint FK_GAZ_NOTIFICARE_OSD_ATR_ON_LOCATIA_2 foreign key (LOCATIA_2_ID) references GAZ_LOCATII(ID)^
alter table GAZ_NOTIFICARE_OSD_ATR add constraint FK_GAZ_NOTIFICARE_OSD_ATR_ON_ID_SOCIETATI_PROIECTARE foreign key (ID_SOCIETATI_PROIECTARE_ID) references GAZ_SOCIETATI_PROIECTARE(ID)^
alter table GAZ_NOTIFICARE_OSD_ATR add constraint FK_GAZ_NOTIFICARE_OSD_ATR_ON_ID_VERIFICATOR foreign key (ID_VERIFICATOR_ID) references GAZ_VERIFICATOR(ID)^
alter table GAZ_NOTIFICARE_OSD_ATR add constraint FK_GAZ_NOTIFICARE_OSD_ATR_ON_ID_SOCIETATI_EXECUTIE foreign key (ID_SOCIETATI_EXECUTIE_ID) references GAZ_SOCIETATI_EXECUTIE(ID)^
create index IDX_GAZ_NOTIFICARE_OSD_ATR_ON_ID_SIRUTA on GAZ_NOTIFICARE_OSD_ATR (ID_SIRUTA_ID)^
create index IDX_GAZ_NOTIFICARE_OSD_ATR_ON_ID_PARTENERI on GAZ_NOTIFICARE_OSD_ATR (ID_PARTENERI_ID)^
create index IDX_GAZ_NOTIFICARE_OSD_ATR_ON_ID_CI_CIF on GAZ_NOTIFICARE_OSD_ATR (ID_CI_CIF_ID)^
create index IDX_GAZ_NOTIFICARE_OSD_ATR_ON_LOCATIA_1 on GAZ_NOTIFICARE_OSD_ATR (LOCATIA_1_ID)^
create index IDX_GAZ_NOTIFICARE_OSD_ATR_ON_ID_TELEFOANE on GAZ_NOTIFICARE_OSD_ATR (ID_TELEFOANE_ID)^
create index IDX_GAZ_NOTIFICARE_OSD_ATR_ON_ID_FAX on GAZ_NOTIFICARE_OSD_ATR (ID_FAX_ID)^
create index IDX_GAZ_NOTIFICARE_OSD_ATR_ON_ID_EMAIL on GAZ_NOTIFICARE_OSD_ATR (ID_EMAIL_ID)^
create index IDX_GAZ_NOTIFICARE_OSD_ATR_ON_ID_ACORD_TEHNIC_RACORDARE on GAZ_NOTIFICARE_OSD_ATR (ID_ACORD_TEHNIC_RACORDARE_ID)^
create index IDX_GAZ_NOTIFICARE_OSD_ATR_ON_LOCATIA_2 on GAZ_NOTIFICARE_OSD_ATR (LOCATIA_2_ID)^
create index IDX_GAZ_NOTIFICARE_OSD_ATR_ON_ID_SOCIETATI_PROIECTARE on GAZ_NOTIFICARE_OSD_ATR (ID_SOCIETATI_PROIECTARE_ID)^
create index IDX_GAZ_NOTIFICARE_OSD_ATR_ON_ID_VERIFICATOR on GAZ_NOTIFICARE_OSD_ATR (ID_VERIFICATOR_ID)^
create index IDX_GAZ_NOTIFICARE_OSD_ATR_ON_ID_SOCIETATI_EXECUTIE on GAZ_NOTIFICARE_OSD_ATR (ID_SOCIETATI_EXECUTIE_ID)^
-- end GAZ_NOTIFICARE_OSD_ATR
-- begin GAZ_SOCIETATI_PROIECTARE
alter table GAZ_SOCIETATI_PROIECTARE add constraint FK_GAZ_SOCIETATI_PROIECTARE_ON_ID_PARTENERI foreign key (ID_PARTENERI_ID) references GAZ_PARTENERI(ID)^
alter table GAZ_SOCIETATI_PROIECTARE add constraint FK_GAZ_SOCIETATI_PROIECTARE_ON_ID_LOCATII foreign key (ID_LOCATII_ID) references GAZ_LOCATII(ID)^
alter table GAZ_SOCIETATI_PROIECTARE add constraint FK_GAZ_SOCIETATI_PROIECTARE_ON_ID_TELEFOANE foreign key (ID_TELEFOANE_ID) references GAZ_TELEFOANE(ID)^
alter table GAZ_SOCIETATI_PROIECTARE add constraint FK_GAZ_SOCIETATI_PROIECTARE_ON_ID_FAX foreign key (ID_FAX_ID) references GAZ_TELEFOANE(ID)^
alter table GAZ_SOCIETATI_PROIECTARE add constraint FK_GAZ_SOCIETATI_PROIECTARE_ON_IDEMAIL foreign key (IDEMAIL_ID) references GAZ_EMAIL(ID)^
alter table GAZ_SOCIETATI_PROIECTARE add constraint FK_GAZ_SOCIETATI_PROIECTARE_ON_ID_CONTURI_BANCARE_PARTENERI foreign key (ID_CONTURI_BANCARE_PARTENERI_ID) references GAZ_CONTURI_BANCARE_PARTENERI(ID)^
alter table GAZ_SOCIETATI_PROIECTARE add constraint FK_GAZ_SOCIETATI_PROIECTARE_ON_ID_REP_LEGAL foreign key (ID_REP_LEGAL_ID) references GAZ_PARTENERI(ID)^
alter table GAZ_SOCIETATI_PROIECTARE add constraint FK_GAZ_SOCIETATI_PROIECTARE_ON_ID_CALITATE_REP_LEGAL foreign key (ID_CALITATE_REP_LEGAL_ID) references GAZ_REP_LEGAL(ID)^
create index IDX_GAZ_SOCIETATI_PROIECTARE_ON_ID_PARTENERI on GAZ_SOCIETATI_PROIECTARE (ID_PARTENERI_ID)^
create index IDX_GAZ_SOCIETATI_PROIECTARE_ON_ID_LOCATII on GAZ_SOCIETATI_PROIECTARE (ID_LOCATII_ID)^
create index IDX_GAZ_SOCIETATI_PROIECTARE_ON_ID_TELEFOANE on GAZ_SOCIETATI_PROIECTARE (ID_TELEFOANE_ID)^
create index IDX_GAZ_SOCIETATI_PROIECTARE_ON_ID_FAX on GAZ_SOCIETATI_PROIECTARE (ID_FAX_ID)^
create index IDX_GAZ_SOCIETATI_PROIECTARE_ON_IDEMAIL on GAZ_SOCIETATI_PROIECTARE (IDEMAIL_ID)^
create index IDX_GAZ_SOCIETATI_PROIECTARE_ON_ID_CONTURI_BANCARE_PARTENERI on GAZ_SOCIETATI_PROIECTARE (ID_CONTURI_BANCARE_PARTENERI_ID)^
create index IDX_GAZ_SOCIETATI_PROIECTARE_ON_ID_REP_LEGAL on GAZ_SOCIETATI_PROIECTARE (ID_REP_LEGAL_ID)^
create index IDX_GAZ_SOCIETATI_PROIECTARE_ON_ID_CALITATE_REP_LEGAL on GAZ_SOCIETATI_PROIECTARE (ID_CALITATE_REP_LEGAL_ID)^
-- end GAZ_SOCIETATI_PROIECTARE
-- begin GAZ_CONTURI_BANCARE_PARTENERI
alter table GAZ_CONTURI_BANCARE_PARTENERI add constraint FK_GAZ_CONTURI_BANCARE_PARTENERI_ON_ID_PARTENERI foreign key (ID_PARTENERI_ID) references GAZ_PARTENERI(ID)^
alter table GAZ_CONTURI_BANCARE_PARTENERI add constraint FK_GAZ_CONTURI_BANCARE_PARTENERI_ON_ID_BANCI foreign key (ID_BANCI_ID) references GAZ_BANCI(ID)^
create index IDX_GAZ_CONTURI_BANCARE_PARTENERI_ON_ID_PARTENERI on GAZ_CONTURI_BANCARE_PARTENERI (ID_PARTENERI_ID)^
create index IDX_GAZ_CONTURI_BANCARE_PARTENERI_ON_ID_BANCI on GAZ_CONTURI_BANCARE_PARTENERI (ID_BANCI_ID)^
-- end GAZ_CONTURI_BANCARE_PARTENERI
-- begin GAZ_SOCIETATI_EXECUTIE
alter table GAZ_SOCIETATI_EXECUTIE add constraint FK_GAZ_SOCIETATI_EXECUTIE_ON_ID_PARTENERI foreign key (ID_PARTENERI_ID) references GAZ_PARTENERI(ID)^
alter table GAZ_SOCIETATI_EXECUTIE add constraint FK_GAZ_SOCIETATI_EXECUTIE_ON_ID_LOCATII foreign key (ID_LOCATII_ID) references GAZ_LOCATII(ID)^
alter table GAZ_SOCIETATI_EXECUTIE add constraint FK_GAZ_SOCIETATI_EXECUTIE_ON_ID_TELEFOANE foreign key (ID_TELEFOANE_ID) references GAZ_TELEFOANE(ID)^
alter table GAZ_SOCIETATI_EXECUTIE add constraint FK_GAZ_SOCIETATI_EXECUTIE_ON_ID_FAX foreign key (ID_FAX_ID) references GAZ_TELEFOANE(ID)^
alter table GAZ_SOCIETATI_EXECUTIE add constraint FK_GAZ_SOCIETATI_EXECUTIE_ON_ID_EMAIL foreign key (ID_EMAIL_ID) references GAZ_EMAIL(ID)^
alter table GAZ_SOCIETATI_EXECUTIE add constraint FK_GAZ_SOCIETATI_EXECUTIE_ON_ID_CONTURI_BANCARE_PARTENERI foreign key (ID_CONTURI_BANCARE_PARTENERI_ID) references GAZ_CONTURI_BANCARE_PARTENERI(ID)^
alter table GAZ_SOCIETATI_EXECUTIE add constraint FK_GAZ_SOCIETATI_EXECUTIE_ON_ID_REP_LEGAL foreign key (ID_REP_LEGAL_ID) references GAZ_PARTENERI(ID)^
alter table GAZ_SOCIETATI_EXECUTIE add constraint FK_GAZ_SOCIETATI_EXECUTIE_ON_ID_CALITATE_REP_LEGAL foreign key (ID_CALITATE_REP_LEGAL_ID) references GAZ_REP_LEGAL(ID)^
create index IDX_GAZ_SOCIETATI_EXECUTIE_ON_ID_PARTENERI on GAZ_SOCIETATI_EXECUTIE (ID_PARTENERI_ID)^
create index IDX_GAZ_SOCIETATI_EXECUTIE_ON_ID_LOCATII on GAZ_SOCIETATI_EXECUTIE (ID_LOCATII_ID)^
create index IDX_GAZ_SOCIETATI_EXECUTIE_ON_ID_TELEFOANE on GAZ_SOCIETATI_EXECUTIE (ID_TELEFOANE_ID)^
create index IDX_GAZ_SOCIETATI_EXECUTIE_ON_ID_FAX on GAZ_SOCIETATI_EXECUTIE (ID_FAX_ID)^
create index IDX_GAZ_SOCIETATI_EXECUTIE_ON_ID_EMAIL on GAZ_SOCIETATI_EXECUTIE (ID_EMAIL_ID)^
create index IDX_GAZ_SOCIETATI_EXECUTIE_ON_ID_CONTURI_BANCARE_PARTENERI on GAZ_SOCIETATI_EXECUTIE (ID_CONTURI_BANCARE_PARTENERI_ID)^
create index IDX_GAZ_SOCIETATI_EXECUTIE_ON_ID_REP_LEGAL on GAZ_SOCIETATI_EXECUTIE (ID_REP_LEGAL_ID)^
create index IDX_GAZ_SOCIETATI_EXECUTIE_ON_ID_CALITATE_REP_LEGAL on GAZ_SOCIETATI_EXECUTIE (ID_CALITATE_REP_LEGAL_ID)^
-- end GAZ_SOCIETATI_EXECUTIE
-- begin GAZ_NOTIFICARE_OSD_ATR_LINII
alter table GAZ_NOTIFICARE_OSD_ATR_LINII add constraint FK_GAZ_NOTIFICARE_OSD_ATR_LINII_ON_ID_NOTIFICARE_OSD_ATR foreign key (ID_NOTIFICARE_OSD_ATR_ID) references GAZ_NOTIFICARE_OSD_ATR(ID)^
alter table GAZ_NOTIFICARE_OSD_ATR_LINII add constraint FK_GAZ_NOTIFICARE_OSD_ATR_LINII_ON_ID_DEN_TARIF foreign key (ID_DEN_TARIF_ID) references GAZ_COMP_TARIF_NOTIFICARE(ID)^
alter table GAZ_NOTIFICARE_OSD_ATR_LINII add constraint FK_GAZ_NOTIFICARE_OSD_ATR_LINII_ON_ID_COTA_TVA foreign key (ID_COTA_TVA_ID) references GAZ_TVA(ID)^
create index IDX_GAZ_NOTIFICARE_OSD_ATR_LINII_ON_ID_NOTIFICARE_OSD_ATR on GAZ_NOTIFICARE_OSD_ATR_LINII (ID_NOTIFICARE_OSD_ATR_ID)^
create index IDX_GAZ_NOTIFICARE_OSD_ATR_LINII_ON_ID_DEN_TARIF on GAZ_NOTIFICARE_OSD_ATR_LINII (ID_DEN_TARIF_ID)^
create index IDX_GAZ_NOTIFICARE_OSD_ATR_LINII_ON_ID_COTA_TVA on GAZ_NOTIFICARE_OSD_ATR_LINII (ID_COTA_TVA_ID)^
-- end GAZ_NOTIFICARE_OSD_ATR_LINII
-- begin GAZ_OFERTE_CONTRACTE_RACORDARE_SD
alter table GAZ_OFERTE_CONTRACTE_RACORDARE_SD add constraint FK_GAZ_OFERTE_CONTRACTE_RACORDARE_SD_ON_ID_SIRUTA foreign key (ID_SIRUTA_ID) references GAZ_SIRUTA(ID)^
alter table GAZ_OFERTE_CONTRACTE_RACORDARE_SD add constraint FK_GAZ_OFERTE_CONTRACTE_RACORDARE_SD_ON_ID_PARTENERI foreign key (ID_PARTENERI_ID) references GAZ_PARTENERI(ID)^
alter table GAZ_OFERTE_CONTRACTE_RACORDARE_SD add constraint FK_GAZ_OFERTE_CONTRACTE_RACORDARE_SD_ON_ID_CI_CIF foreign key (ID_CI_CIF_ID) references GAZ_CI_CIF(ID)^
alter table GAZ_OFERTE_CONTRACTE_RACORDARE_SD add constraint FK_GAZ_OFERTE_CONTRACTE_RACORDARE_SD_ON_LOCATIA_1 foreign key (LOCATIA_1_ID) references GAZ_LOCATII(ID)^
alter table GAZ_OFERTE_CONTRACTE_RACORDARE_SD add constraint FK_GAZ_OFERTE_CONTRACTE_RACORDARE_SD_ON_ID_TELEFOANE foreign key (ID_TELEFOANE_ID) references GAZ_TELEFOANE(ID)^
alter table GAZ_OFERTE_CONTRACTE_RACORDARE_SD add constraint FK_GAZ_OFERTE_CONTRACTE_RACORDARE_SD_ON_ID_FAX foreign key (ID_FAX_ID) references GAZ_TELEFOANE(ID)^
alter table GAZ_OFERTE_CONTRACTE_RACORDARE_SD add constraint FK_GAZ_OFERTE_CONTRACTE_RACORDARE_SD_ON_ID_EMAIL foreign key (ID_EMAIL_ID) references GAZ_EMAIL(ID)^
alter table GAZ_OFERTE_CONTRACTE_RACORDARE_SD add constraint FK_GAZ_OFERTCONTRRACORSD_ON_ID_CONTURI_BANCARE_PARTENERI foreign key (ID_CONTURI_BANCARE_PARTENERI_ID) references GAZ_CONTURI_BANCARE_PARTENERI(ID)^
alter table GAZ_OFERTE_CONTRACTE_RACORDARE_SD add constraint FK_GAZ_OFERTCONTRRACORSD_ON_ID_ACORD_TEHNIC_RACORDARE foreign key (ID_ACORD_TEHNIC_RACORDARE_ID) references GAZ_ACORD_TEHNIC_RACORDARE(ID)^
alter table GAZ_OFERTE_CONTRACTE_RACORDARE_SD add constraint FK_GAZ_OFERTE_CONTRACTE_RACORDARE_SD_ON_LOCATIA_2 foreign key (LOCATIA_2_ID) references GAZ_LOCATII(ID)^
alter table GAZ_OFERTE_CONTRACTE_RACORDARE_SD add constraint FK_GAZ_OFERCONTRACOSD_ON_IDSTATOFERCONTRACOSD1 foreign key (ID_STATUS_OFERTE_CONTRACTE_RACORDARE_SD_ID) references GAZ_STATUS_OFERTE_CONTRACTE_RACORDARE_SD(ID)^
create index IDX_GAZ_OFERTE_CONTRACTE_RACORDARE_SD_ON_ID_SIRUTA on GAZ_OFERTE_CONTRACTE_RACORDARE_SD (ID_SIRUTA_ID)^
create index IDX_GAZ_OFERTE_CONTRACTE_RACORDARE_SD_ON_ID_PARTENERI on GAZ_OFERTE_CONTRACTE_RACORDARE_SD (ID_PARTENERI_ID)^
create index IDX_GAZ_OFERTE_CONTRACTE_RACORDARE_SD_ON_ID_CI_CIF on GAZ_OFERTE_CONTRACTE_RACORDARE_SD (ID_CI_CIF_ID)^
create index IDX_GAZ_OFERTE_CONTRACTE_RACORDARE_SD_ON_LOCATIA_1 on GAZ_OFERTE_CONTRACTE_RACORDARE_SD (LOCATIA_1_ID)^
create index IDX_GAZ_OFERTE_CONTRACTE_RACORDARE_SD_ON_ID_TELEFOANE on GAZ_OFERTE_CONTRACTE_RACORDARE_SD (ID_TELEFOANE_ID)^
create index IDX_GAZ_OFERTE_CONTRACTE_RACORDARE_SD_ON_ID_FAX on GAZ_OFERTE_CONTRACTE_RACORDARE_SD (ID_FAX_ID)^
create index IDX_GAZ_OFERTE_CONTRACTE_RACORDARE_SD_ON_ID_EMAIL on GAZ_OFERTE_CONTRACTE_RACORDARE_SD (ID_EMAIL_ID)^
create index IDX_GAZ_OFERTCONTRRACORSD_ON_ID_CONTURI_BANCARE_PARTENERI on GAZ_OFERTE_CONTRACTE_RACORDARE_SD (ID_CONTURI_BANCARE_PARTENERI_ID)^
create index IDX_GAZ_OFERTCONTRRACORSD_ON_ID_ACORD_TEHNIC_RACORDARE on GAZ_OFERTE_CONTRACTE_RACORDARE_SD (ID_ACORD_TEHNIC_RACORDARE_ID)^
create index IDX_GAZ_OFERTE_CONTRACTE_RACORDARE_SD_ON_LOCATIA_2 on GAZ_OFERTE_CONTRACTE_RACORDARE_SD (LOCATIA_2_ID)^
create index IDX_GAZ_OFERCONTRACOSD_ON_IDSTATOFERCONTRACOSD1 on GAZ_OFERTE_CONTRACTE_RACORDARE_SD (ID_STATUS_OFERTE_CONTRACTE_RACORDARE_SD_ID)^
-- end GAZ_OFERTE_CONTRACTE_RACORDARE_SD
-- begin GAZ_TARIFE_RACORDARE_FIXE
alter table GAZ_TARIFE_RACORDARE_FIXE add constraint FK_GAZ_TARIFE_RACORDARE_FIXE_ON_ID_SIRUTA foreign key (ID_SIRUTA_ID) references GAZ_SIRUTA(ID)^
create index IDX_GAZ_TARIFE_RACORDARE_FIXE_ON_ID_SIRUTA on GAZ_TARIFE_RACORDARE_FIXE (ID_SIRUTA_ID)^
-- end GAZ_TARIFE_RACORDARE_FIXE
-- begin GAZ_OFERTE_CONTRACTE_RACORDARE_OSD_LINII
alter table GAZ_OFERTE_CONTRACTE_RACORDARE_OSD_LINII add constraint FK_GAZ_OFERCONTRACOOSDLINI_ON_ID_OFERTE_CONTRACTE_RACORDARE_SD foreign key (ID_OFERTE_CONTRACTE_RACORDARE_SD_ID) references GAZ_OFERTE_CONTRACTE_RACORDARE_SD(ID)^
alter table GAZ_OFERTE_CONTRACTE_RACORDARE_OSD_LINII add constraint FK_GAZ_OFERTCONTRRACOROSDLINII_ON_ID_TARIFE_RACORDARE_FIXE foreign key (ID_TARIFE_RACORDARE_FIXE_ID) references GAZ_TARIFE_RACORDARE_FIXE(ID)^
alter table GAZ_OFERTE_CONTRACTE_RACORDARE_OSD_LINII add constraint FK_GAZ_OFERTE_CONTRACTE_RACORDARE_OSD_LINII_ON_ID_TVA foreign key (ID_TVA_ID) references GAZ_TVA(ID)^
create index IDX_GAZ_OFERCONTRACOOSDLINI_ON_IDOFERCONTRACOSD on GAZ_OFERTE_CONTRACTE_RACORDARE_OSD_LINII (ID_OFERTE_CONTRACTE_RACORDARE_SD_ID)^
create index IDX_GAZ_OFERTCONTRRACOROSDLINII_ON_ID_TARIFE_RACORDARE_FIXE on GAZ_OFERTE_CONTRACTE_RACORDARE_OSD_LINII (ID_TARIFE_RACORDARE_FIXE_ID)^
create index IDX_GAZ_OFERTE_CONTRACTE_RACORDARE_OSD_LINII_ON_ID_TVA on GAZ_OFERTE_CONTRACTE_RACORDARE_OSD_LINII (ID_TVA_ID)^
-- end GAZ_OFERTE_CONTRACTE_RACORDARE_OSD_LINII
-- begin GAZ_TARIFE_EXECUTIE_BRANSAMENTE
alter table GAZ_TARIFE_EXECUTIE_BRANSAMENTE add constraint FK_GAZ_TARIFE_EXECUTIE_BRANSAMENTE_ON_ID_SIRUTA foreign key (ID_SIRUTA_ID) references GAZ_SIRUTA(ID)^
alter table GAZ_TARIFE_EXECUTIE_BRANSAMENTE add constraint FK_GAZ_TARIFE_EXECUTIE_BRANSAMENTE_ON_ID_DIAM_PE foreign key (ID_DIAM_PE_ID) references GAZ_DIAM_PE(ID)^
alter table GAZ_TARIFE_EXECUTIE_BRANSAMENTE add constraint FK_GAZ_TARIFE_EXECUTIE_BRANSAMENTE_ON_ID_DIAM_OL foreign key (ID_DIAM_OL_ID) references GAZ_DIAM_OL(ID)^
create index IDX_GAZ_TARIFE_EXECUTIE_BRANSAMENTE_ON_ID_SIRUTA on GAZ_TARIFE_EXECUTIE_BRANSAMENTE (ID_SIRUTA_ID)^
create index IDX_GAZ_TARIFE_EXECUTIE_BRANSAMENTE_ON_ID_DIAM_PE on GAZ_TARIFE_EXECUTIE_BRANSAMENTE (ID_DIAM_PE_ID)^
create index IDX_GAZ_TARIFE_EXECUTIE_BRANSAMENTE_ON_ID_DIAM_OL on GAZ_TARIFE_EXECUTIE_BRANSAMENTE (ID_DIAM_OL_ID)^
-- end GAZ_TARIFE_EXECUTIE_BRANSAMENTE
-- begin GAZ_TARIFE_EXECUTIE_POSTURI
alter table GAZ_TARIFE_EXECUTIE_POSTURI add constraint FK_GAZ_TARIFE_EXECUTIE_POSTURI_ON_ID_SIRUTA foreign key (ID_SIRUTA_ID) references GAZ_SIRUTA(ID)^
create index IDX_GAZ_TARIFE_EXECUTIE_POSTURI_ON_ID_SIRUTA on GAZ_TARIFE_EXECUTIE_POSTURI (ID_SIRUTA_ID)^
-- end GAZ_TARIFE_EXECUTIE_POSTURI
-- begin GAZ_OFERTE_CON_RAC_OSD_TARIF_EXE_BR_LINII
alter table GAZ_OFERTE_CON_RAC_OSD_TARIF_EXE_BR_LINII add constraint FK_GAZ_OFECONRACOSDTAREXEBRLIN_ON_IDOFECONRACSD foreign key (ID_OFERTE_CONTRACTE_RACORDARE_SD_ID) references GAZ_OFERTE_CONTRACTE_RACORDARE_SD(ID)^
alter table GAZ_OFERTE_CON_RAC_OSD_TARIF_EXE_BR_LINII add constraint FK_GAZ_OFERCONRACOSDTARIEXEBRLINI_ON_IDTARIEXECBRAN foreign key (ID_TARIFE_EXECUTIE_BRANSAMENTE_ID) references GAZ_TARIFE_EXECUTIE_BRANSAMENTE(ID)^
alter table GAZ_OFERTE_CON_RAC_OSD_TARIF_EXE_BR_LINII add constraint FK_GAZ_OFERTE_CON_RAC_OSD_TARIF_EXE_BR_LINII_ON_ID_TVA foreign key (ID_TVA_ID) references GAZ_TVA(ID)^
create index IDX_GAZ_OFECONRACOSDTAREXEBRLIN_ON_IDOFECONRACSD on GAZ_OFERTE_CON_RAC_OSD_TARIF_EXE_BR_LINII (ID_OFERTE_CONTRACTE_RACORDARE_SD_ID)^
create index IDX_GAZ_OFERCONRACOSDTARIEXEBRLINI_ON_IDTARIEXECBRAN on GAZ_OFERTE_CON_RAC_OSD_TARIF_EXE_BR_LINII (ID_TARIFE_EXECUTIE_BRANSAMENTE_ID)^
create index IDX_GAZ_OFERTE_CON_RAC_OSD_TARIF_EXE_BR_LINII_ON_ID_TVA on GAZ_OFERTE_CON_RAC_OSD_TARIF_EXE_BR_LINII (ID_TVA_ID)^
-- end GAZ_OFERTE_CON_RAC_OSD_TARIF_EXE_BR_LINII
-- begin GAZ_OFERTE_CON_RAC_OSD_TARIF_EXE_POST_LINII
alter table GAZ_OFERTE_CON_RAC_OSD_TARIF_EXE_POST_LINII add constraint FK_GAZ_OFECONRACOSDTAREXEPOSLIN_ON_IDOFECONRACSD foreign key (ID_OFERTE_CONTRACTE_RACORDARE_SD_ID) references GAZ_OFERTE_CONTRACTE_RACORDARE_SD(ID)^
alter table GAZ_OFERTE_CON_RAC_OSD_TARIF_EXE_POST_LINII add constraint FK_GAZ_OFERCONRACOSDTARIEXEPOSTLINI_ON_IDTARIEXECPOST foreign key (ID_TARIFE_EXECUTIE_POSTURI_ID) references GAZ_TARIFE_EXECUTIE_POSTURI(ID)^
alter table GAZ_OFERTE_CON_RAC_OSD_TARIF_EXE_POST_LINII add constraint FK_GAZ_OFERTE_CON_RAC_OSD_TARIF_EXE_POST_LINII_ON_ID_TVA foreign key (ID_TVA_ID) references GAZ_TVA(ID)^
create index IDX_GAZ_OFECONRACOSDTAREXEPOSLIN_ON_IDOFECONRACSD on GAZ_OFERTE_CON_RAC_OSD_TARIF_EXE_POST_LINII (ID_OFERTE_CONTRACTE_RACORDARE_SD_ID)^
create index IDX_GAZ_OFERCONRACOSDTARIEXEPOSTLINI_ON_IDTARIEXECPOST on GAZ_OFERTE_CON_RAC_OSD_TARIF_EXE_POST_LINII (ID_TARIFE_EXECUTIE_POSTURI_ID)^
create index IDX_GAZ_OFERTE_CON_RAC_OSD_TARIF_EXE_POST_LINII_ON_ID_TVA on GAZ_OFERTE_CON_RAC_OSD_TARIF_EXE_POST_LINII (ID_TVA_ID)^
-- end GAZ_OFERTE_CON_RAC_OSD_TARIF_EXE_POST_LINII
-- begin GAZ_EXECUTANT
alter table GAZ_EXECUTANT add constraint FK_GAZ_EXECUTANT_ON_ID_SOCIETATI_EXECUTIE foreign key (ID_SOCIETATI_EXECUTIE_ID) references GAZ_SOCIETATI_EXECUTIE(ID)^
create index IDX_GAZ_EXECUTANT_ON_ID_SOCIETATI_EXECUTIE on GAZ_EXECUTANT (ID_SOCIETATI_EXECUTIE_ID)^
-- end GAZ_EXECUTANT
-- begin GAZ_PROIECTANT
alter table GAZ_PROIECTANT add constraint FK_GAZ_PROIECTANT_ON_ID_SOCIETATI_PROIECTARE foreign key (ID_SOCIETATI_PROIECTARE_ID) references GAZ_SOCIETATI_PROIECTARE(ID)^
create index IDX_GAZ_PROIECTANT_ON_ID_SOCIETATI_PROIECTARE on GAZ_PROIECTANT (ID_SOCIETATI_PROIECTARE_ID)^
-- end GAZ_PROIECTANT
-- begin GAZ_INSTALATORI_OSD
alter table GAZ_INSTALATORI_OSD add constraint FK_GAZ_INSTALATORI_OSD_ON_ID_SIRUTA foreign key (ID_SIRUTA_ID) references GAZ_SIRUTA(ID)^
alter table GAZ_INSTALATORI_OSD add constraint FK_GAZ_INSTALATORI_OSD_ON_ID_PARTENERI foreign key (ID_PARTENERI_ID) references GAZ_PARTENERI(ID)^
create index IDX_GAZ_INSTALATORI_OSD_ON_ID_SIRUTA on GAZ_INSTALATORI_OSD (ID_SIRUTA_ID)^
create index IDX_GAZ_INSTALATORI_OSD_ON_ID_PARTENERI on GAZ_INSTALATORI_OSD (ID_PARTENERI_ID)^
-- end GAZ_INSTALATORI_OSD
-- begin GAZ_BANCI
create unique index IDX_GAZ_BANCI_UK_DEN_UZUALA on GAZ_BANCI (DEN_UZUALA) where DELETE_TS is null ^
-- end GAZ_BANCI
-- begin GAZ_COMP_TARIF_NOTIFICARE
alter table GAZ_COMP_TARIF_NOTIFICARE add constraint FK_GAZ_COMP_TARIF_NOTIFICARE_ON_ID_SIRUTA foreign key (ID_SIRUTA_ID) references GAZ_SIRUTA(ID)^
create index IDX_GAZ_COMP_TARIF_NOTIFICARE_ON_ID_SIRUTA on GAZ_COMP_TARIF_NOTIFICARE (ID_SIRUTA_ID)^
-- end GAZ_COMP_TARIF_NOTIFICARE
-- begin GAZ_CONTRACTE_SERVICII_OE
alter table GAZ_CONTRACTE_SERVICII_OE add constraint FK_GAZ_CONTRACTE_SERVICII_OE_ON_ID_SIRUTA foreign key (ID_SIRUTA_ID) references GAZ_SIRUTA(ID)^
alter table GAZ_CONTRACTE_SERVICII_OE add constraint FK_GAZ_CONTRACTE_SERVICII_OE_ON_ID_SOCIETATI_PROIECTARE foreign key (ID_SOCIETATI_PROIECTARE_ID) references GAZ_SOCIETATI_PROIECTARE(ID)^
alter table GAZ_CONTRACTE_SERVICII_OE add constraint FK_GAZ_CONTRACTE_SERVICII_OE_ON_ID_VERIFICATOR foreign key (ID_VERIFICATOR_ID) references GAZ_VERIFICATOR(ID)^
alter table GAZ_CONTRACTE_SERVICII_OE add constraint FK_GAZ_CONTRACTE_SERVICII_OE_ON_ID_SOCIETATI_EXECUTIE foreign key (ID_SOCIETATI_EXECUTIE_ID) references GAZ_SOCIETATI_EXECUTIE(ID)^
alter table GAZ_CONTRACTE_SERVICII_OE add constraint FK_GAZ_CONTRACTE_SERVICII_OE_ON_ID_NOTIFICARE_OSD_ATR foreign key (ID_NOTIFICARE_OSD_ATR_ID) references GAZ_NOTIFICARE_OSD_ATR(ID)^
alter table GAZ_CONTRACTE_SERVICII_OE add constraint FK_GAZ_CONTRACTE_SERVICII_OE_ON_ID_ACORD_TEHNIC_RACORDARE foreign key (ID_ACORD_TEHNIC_RACORDARE_ID) references GAZ_ACORD_TEHNIC_RACORDARE(ID)^
alter table GAZ_CONTRACTE_SERVICII_OE add constraint FK_GAZ_CONTRACTE_SERVICII_OE_ON_ID_CONTRACTE_RACORDARE_SD foreign key (ID_CONTRACTE_RACORDARE_SD_ID) references GAZ_CONTRACTE_RACORDARE_SD(ID)^
alter table GAZ_CONTRACTE_SERVICII_OE add constraint FK_GAZ_CONTRACTE_SERVICII_OE_ON_LOCATIA_2 foreign key (LOCATIA_2_ID) references GAZ_LOCATII(ID)^
alter table GAZ_CONTRACTE_SERVICII_OE add constraint FK_GAZ_CONTRSERVIOE_ON_ID_STATUS_CONTRACTE_SERVICII_OE1 foreign key (ID_STATUS_CONTRACTE_SERVICII_OE_ID) references GAZ_STATUS_CONTRACTE_SERVICII_OE(ID)^
create index IDX_GAZ_CONTRACTE_SERVICII_OE_ON_ID_SIRUTA on GAZ_CONTRACTE_SERVICII_OE (ID_SIRUTA_ID)^
create index IDX_GAZ_CONTRACTE_SERVICII_OE_ON_ID_SOCIETATI_PROIECTARE on GAZ_CONTRACTE_SERVICII_OE (ID_SOCIETATI_PROIECTARE_ID)^
create index IDX_GAZ_CONTRACTE_SERVICII_OE_ON_ID_VERIFICATOR on GAZ_CONTRACTE_SERVICII_OE (ID_VERIFICATOR_ID)^
create index IDX_GAZ_CONTRACTE_SERVICII_OE_ON_ID_SOCIETATI_EXECUTIE on GAZ_CONTRACTE_SERVICII_OE (ID_SOCIETATI_EXECUTIE_ID)^
create index IDX_GAZ_CONTRACTE_SERVICII_OE_ON_ID_NOTIFICARE_OSD_ATR on GAZ_CONTRACTE_SERVICII_OE (ID_NOTIFICARE_OSD_ATR_ID)^
create index IDX_GAZ_CONTRACTE_SERVICII_OE_ON_ID_ACORD_TEHNIC_RACORDARE on GAZ_CONTRACTE_SERVICII_OE (ID_ACORD_TEHNIC_RACORDARE_ID)^
create index IDX_GAZ_CONTRACTE_SERVICII_OE_ON_ID_CONTRACTE_RACORDARE_SD on GAZ_CONTRACTE_SERVICII_OE (ID_CONTRACTE_RACORDARE_SD_ID)^
create index IDX_GAZ_CONTRACTE_SERVICII_OE_ON_LOCATIA_2 on GAZ_CONTRACTE_SERVICII_OE (LOCATIA_2_ID)^
create index IDX_GAZ_CONTRSERVIOE_ON_ID_STATUS_CONTRACTE_SERVICII_OE1 on GAZ_CONTRACTE_SERVICII_OE (ID_STATUS_CONTRACTE_SERVICII_OE_ID)^
-- end GAZ_CONTRACTE_SERVICII_OE
-- begin GAZ_VERIFICATOR
alter table GAZ_VERIFICATOR add constraint FK_GAZ_VERIFICATOR_ON_ID_NUME_VERIFICATOR foreign key (ID_NUME_VERIFICATOR_ID) references GAZ_PARTENERI(ID)^
alter table GAZ_VERIFICATOR add constraint FK_GAZ_VERIFICATOR_ON_ID_CONTURI_BANCARE_PARTENERI foreign key (ID_CONTURI_BANCARE_PARTENERI_ID) references GAZ_CONTURI_BANCARE_PARTENERI(ID)^
alter table GAZ_VERIFICATOR add constraint FK_GAZ_VERIFICATOR_ON_ID_LOCATII foreign key (ID_LOCATII_ID) references GAZ_LOCATII(ID)^
alter table GAZ_VERIFICATOR add constraint FK_GAZ_VERIFICATOR_ON_ID_TELEFOANE foreign key (ID_TELEFOANE_ID) references GAZ_TELEFOANE(ID)^
alter table GAZ_VERIFICATOR add constraint FK_GAZ_VERIFICATOR_ON_ID_FAX foreign key (ID_FAX_ID) references GAZ_TELEFOANE(ID)^
alter table GAZ_VERIFICATOR add constraint FK_GAZ_VERIFICATOR_ON_ID_EMAIL foreign key (ID_EMAIL_ID) references GAZ_EMAIL(ID)^
create index IDX_GAZ_VERIFICATOR_ON_ID_NUME_VERIFICATOR on GAZ_VERIFICATOR (ID_NUME_VERIFICATOR_ID)^
create index IDX_GAZ_VERIFICATOR_ON_ID_CONTURI_BANCARE_PARTENERI on GAZ_VERIFICATOR (ID_CONTURI_BANCARE_PARTENERI_ID)^
create index IDX_GAZ_VERIFICATOR_ON_ID_LOCATII on GAZ_VERIFICATOR (ID_LOCATII_ID)^
create index IDX_GAZ_VERIFICATOR_ON_ID_TELEFOANE on GAZ_VERIFICATOR (ID_TELEFOANE_ID)^
create index IDX_GAZ_VERIFICATOR_ON_ID_FAX on GAZ_VERIFICATOR (ID_FAX_ID)^
create index IDX_GAZ_VERIFICATOR_ON_ID_EMAIL on GAZ_VERIFICATOR (ID_EMAIL_ID)^
-- end GAZ_VERIFICATOR
-- begin GAZ_STATUS_CERERE_ATR
create unique index IDX_GAZ_STATUS_CERERE_ATR_UK_NR_ORD on GAZ_STATUS_CERERE_ATR (NR_ORD) where DELETE_TS is null ^
create unique index IDX_GAZ_STATUS_CERERE_ATR_UK_STARE_CERERE_ATR on GAZ_STATUS_CERERE_ATR (STARE_CERERE_ATR) where DELETE_TS is null ^
-- end GAZ_STATUS_CERERE_ATR
-- begin GAZ_STATUS_CONTRACTE_RACORDARE_SD
create unique index IDX_GAZ_STATUS_CONTRACTE_RACORDARE_SD_UK_NR_ORD on GAZ_STATUS_CONTRACTE_RACORDARE_SD (NR_ORD) where DELETE_TS is null ^
create unique index IDX_GAZ_STATUCONTRRACORSD_UK_STARE_CONTRACT_RACORDARE_SD on GAZ_STATUS_CONTRACTE_RACORDARE_SD (STARE_CONTRACT_RACORDARE_SD) where DELETE_TS is null ^
-- end GAZ_STATUS_CONTRACTE_RACORDARE_SD
-- begin GAZ_STATUS_CONTRACTE_SERVICII_OE
create unique index IDX_GAZ_STATUS_CONTRACTE_SERVICII_OE_UK_NR_ORD on GAZ_STATUS_CONTRACTE_SERVICII_OE (NR_ORD) where DELETE_TS is null ^
create unique index IDX_GAZ_STATUCONTRSERVIOE_UK_STARE_CONTRACTE_SERVICII_OE1 on GAZ_STATUS_CONTRACTE_SERVICII_OE (STARE_CONTRACTE_SERVICII_OE) where DELETE_TS is null ^
-- end GAZ_STATUS_CONTRACTE_SERVICII_OE
-- begin GAZ_STATUS_OFERTE_CONTRACTE_RACORDARE_SD
create unique index IDX_GAZ_STATUS_OFERTE_CONTRACTE_RACORDARE_SD_UK_NR_ORD on GAZ_STATUS_OFERTE_CONTRACTE_RACORDARE_SD (NR_ORD) where DELETE_TS is null ^
create unique index IDX_GAZ_STATOFERCONTRACOSD_UK_STAROFERCONTRACOSD on GAZ_STATUS_OFERTE_CONTRACTE_RACORDARE_SD (STARE_OFERTE_CONTRACTE_RACORDARE_SD) where DELETE_TS is null ^
-- end GAZ_STATUS_OFERTE_CONTRACTE_RACORDARE_SD
